// GENERATED FILE — do not edit.  Regenerate:  ./scripts/paper-figs
// Source of truth: diag/paperfigs/manifest.tsv (crop boxes) and diag/*.lean
// (docstrings).  The .png clips and .doc.txt sidecars it reads are regenerated too.

#set page(width: 29.7cm, height: auto, margin: 1.4cm)
#set text(size: 9.5pt)
#set par(justify: true)
#show raw: set text(size: 8pt)

#let figdir = "paperfigs/"
#let clip(name, w) = image(figdir + name + ".png", width: w)
#let doc(name) = text(8.2pt, read(figdir + name + ".doc.txt"))
#let src(s) = text(7.5pt, luma(100))[#s]
#show figure: set figure(numbering: none)
#show figure.caption: it => it.body

#align(center)[
  #text(15pt)[*Axiom crosscheck — source figure against Lean field*] \
  #src[generated by `scripts/paper-figs`; papers cited by file name, never by arXiv id]
]

Left column: the figure as printed, clipped from the paper at 150 dpi.  Right column: the
docstring of the Lean declaration transcribed from it, verbatim.  Reading a row across is the
check — the picture and the equation number in the docstring must be the same equation.

= Cartesian bicategories of relations

#table(
  columns: (auto, auto, 1fr),
  align: (center + horizon, left + horizon, left + top),
  inset: 6pt, stroke: 0.4pt + luma(190),
  table.header([*source clip*], [*Lean declaration*], [*its docstring*]),
  clip("fs-def41-delta", 0.90in),
  [`Freyd.Diag.CartBicat.Δ` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 17]],
  src[no docstring — declaration not found in `diag/`],
  clip("fs-def41-bang", 0.90in),
  [`Freyd.Diag.CartBicat.«!»` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 17]],
  src[no docstring — declaration not found in `diag/`],
  clip("fs-def41-nabla", 0.90in),
  [`Freyd.Diag.CartBicat.«∇»` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 17]],
  src[no docstring — declaration not found in `diag/`],
  clip("fs-def41-unitR", 0.90in),
  [`Freyd.Diag.CartBicat.«?»` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 17]],
  src[no docstring — declaration not found in `diag/`],
  clip("fs-eq05", 1.53in),
  [`Freyd.Diag.CartBicat.«∇_assoc»` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 8]],
  doc("fs-eq05"),
  clip("fs-eq06", 1.67in),
  [`Freyd.Diag.CartBicat.«∇_comm»` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 8]],
  doc("fs-eq06"),
  clip("fs-eq07", 1.73in),
  [`Freyd.Diag.CartBicat.«∇_unit»` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 8]],
  doc("fs-eq07"),
  clip("fs-eq08", 1.53in),
  [`Freyd.Diag.CartBicat.Δ_assoc` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 8]],
  src[no docstring — declaration not found in `diag/`],
  clip("fs-eq09", 1.60in),
  [`Freyd.Diag.CartBicat.Δ_comm` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 8]],
  doc("fs-eq09"),
  clip("fs-eq10", 1.73in),
  [`Freyd.Diag.CartBicat.Δ_counit` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 8]],
  doc("fs-eq10"),
  clip("fs-eq11", 2.53in),
  [`Freyd.Diag.CartBicat.frob_left` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 8]],
  doc("fs-eq11"),
  clip("fs-eq12", 2.20in),
  [`Freyd.Diag.CartBicat.special` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 8]],
  doc("fs-eq12"),
  clip("fs-ineq37", 2.17in),
  [`Freyd.Diag.CartBicat.«∇Δ_≤_𝟙»` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 18]],
  doc("fs-ineq37"),
  clip("fs-ineq38", 2.37in),
  [`Freyd.Diag.CartBicat.«𝟙_≤_Δ∇»` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 18]],
  doc("fs-ineq38"),
  clip("fs-ineq39", 2.17in),
  [`Freyd.Diag.CartBicat.«?!_≤_𝟙»` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 18]],
  doc("fs-ineq39"),
  clip("fs-ineq40", 2.37in),
  [`Freyd.Diag.CartBicat.«𝟙_≤_!?»` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 18]],
  doc("fs-ineq40"),
  clip("fs-eq41-left", 1.55in),
  [`Freyd.Diag.CartBicat.frob_left` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 18]],
  doc("fs-eq41-left"),
  clip("fs-eq41-right", 1.70in),
  [`Freyd.Diag.CartBicat.frob_right` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 18]],
  doc("fs-eq41-right"),
  clip("fs-ineq42", 2.73in),
  [`Freyd.Diag.CartBicat.lax_Δ` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 18]],
  doc("fs-ineq42"),
  clip("fs-ineq43", 2.37in),
  [`Freyd.Diag.CartBicat.lax_!` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 18]],
  doc("fs-ineq43"),
  clip("fs-eq03-delta", 2.48in),
  [`Freyd.Diag.CartBicat.lax_Δ` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 4]],
  doc("fs-eq03-delta"),
  clip("fs-eq03-bang", 1.93in),
  [`Freyd.Diag.CartBicat.lax_!` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 4]],
  doc("fs-eq03-bang"),
  clip("fs-special-derivation", 3.60in),
  [`Freyd.Diag.CartBicat.special` \ #src[functorialSemanticsForRelationalTheories.pdf] \ #src[p. 18]],
  doc("fs-special-derivation"),
  clip("fol-fig2", 4.80in),
  [`Freyd.Diag.CartBicat` \ #src[DiagrammaticAlgebraOfFirstOrderLogic.pdf] \ #src[p. 6]],
  doc("fol-fig2"),
  clip("fol-fig3", 4.80in),
  [`Freyd.Diag.CocartBicat` \ #src[DiagrammaticAlgebraOfFirstOrderLogic.pdf] \ #src[p. 6]],
  doc("fol-fig3"),
  clip("fol-fig4", 4.80in),
  [`Freyd.Diag.LinearBicat` \ #src[DiagrammaticAlgebraOfFirstOrderLogic.pdf] \ #src[p. 7]],
  doc("fol-fig4"),
  clip("fol-fig5", 4.80in),
  [`Freyd.Diag.FOBicat` \ #src[DiagrammaticAlgebraOfFirstOrderLogic.pdf] \ #src[p. 9]],
  doc("fol-fig5"),
  clip("tape-fig3", 4.80in),
  [`Freyd.Diag.CartBicat` \ #src[TapeDiagrams.pdf] \ #src[p. 6]],
  doc("tape-fig3"),
)

= Sources recorded for later phases

No Lean counterpart yet: the tape layer (`diag/Tape.lean`) and the first-order layer
(`diag/FO.lean`) are unwritten, and Example 2.3(d)(e) is the road Definition 4.1 does not take
— the same monoid and comonoid combined as a bialgebra rather than as a Frobenius algebra.

#figure(clip("fs-eq13-14", 2.00in), caption: src[functorialSemanticsForRelationalTheories.pdf p. 8])

#figure(clip("fs-eq15-16", 2.43in), caption: src[functorialSemanticsForRelationalTheories.pdf p. 8])

#figure(clip("fs-eq17-19", 5.33in), caption: src[functorialSemanticsForRelationalTheories.pdf p. 9])

#figure(clip("fol-fig9", 6.20in), caption: src[DiagrammaticAlgebraOfFirstOrderLogic.pdf p. 15])

#figure(clip("tape-fig1", 5.37in), caption: src[TapeDiagrams.pdf p. 6])

#figure(clip("tape-fig2", 5.37in), caption: src[TapeDiagrams.pdf p. 6])

