/-
  Mathlib-free ultrafilter infrastructure for §1.646.

  ## Why this file exists

  §1.646's representation needs: `I` = the (directed) index of finite sets of proper subobjects, a
  proper filter `F₀` on `I` of "principal coideals", and an ULTRAFILTER `F ⊇ F₀`, so the ultrapower
  `Tᶠ` is faithful (S1_64.lean:113-124).  Freyd treats ultrafilters as ambient set theory and uses
  choice freely; mathlib supplies them but the repo is deliberately mathlib-free.

  This file builds, from `Classical.choice` ALONE:

  * `Filter I`              — a proper filter (sets-of-subsets style, via `Sub I = I → Prop`).
  * `Ultrafilter I`         — a maximal proper filter; equivalently `∀ S, S ∈ F ∨ Sᶜ ∈ F`.
  * `exists_ultrafilter_le` — every proper filter extends to an ultrafilter (Zorn / Bourbaki–Witt).

  ## Method

  The repo has no reusable Zorn lemma, so we develop a MINIMAL Zorn's lemma inline by the same
  Bourbaki–Witt tower fixpoint used in `Freyd/WellOrdering.lean`: a choice function picks a strict
  upper bound whenever one exists; towers of iterated picks form a chain; their union is a chain with
  an upper bound `u`; `u` admits no strict upper bound, i.e. is maximal.  Specialised to the poset of
  proper filters `⊇ F₀` (chains closed under union of filters), the maximal element is an ultrafilter.
-/
import Freyd.S1_543_WellOrdering

namespace Freyd.UF

universe u

/-\! ## The boolean operations a filter needs

`Sub I = I → Prop` (a subset as a predicate) with `⊆ₛ`, `ext`, `Subset.refl`, `Subset.trans` comes
from `Freyd.Sub` (§1.543); only the operations specific to filters are here.  Their notations stay
local to this file — a global `ᶜ` would clash with the Heyting complement. -/

variable {I : Type u}

/-- The whole index set. -/
def univ : Sub I := fun _ => True
/-- The empty set. -/
def empty : Sub I := fun _ => False
/-- Complement. -/
def compl (s : Sub I) : Sub I := fun a => ¬ s a
@[inherit_doc] postfix:max "ᶜ" => compl
/-- Binary intersection. -/
def inter (s t : Sub I) : Sub I := fun a => s a ∧ t a
@[inherit_doc] infixl:70 " ∩ᵤ " => inter

theorem mem_univ (a : I) : univ a := trivial
theorem inter_subset_left {s t : Sub I} : s ∩ᵤ t ⊆ₛ s := fun _ h => h.1
theorem inter_subset_right {s t : Sub I} : s ∩ᵤ t ⊆ₛ t := fun _ h => h.2

/-\! ## Filters and ultrafilters -/

/-- A proper filter on `I`. -/
structure Filter (I : Type u) where
  /-- The sets belonging to the filter. -/
  sets : Sub I → Prop
  /-- The filter is proper: the empty set is not a member. -/
  empty_not_mem : ¬ sets empty
  /-- The whole set is a member. -/
  univ_mem : sets univ
  /-- Upward closed: a superset of a member is a member. -/
  up_closed : ∀ {s t}, sets s → s ⊆ₛ t → sets t
  /-- Closed under binary intersection. -/
  inter_mem : ∀ {s t}, sets s → sets t → sets (s ∩ᵤ t)

namespace Filter
variable {I : Type u}

/-- Membership: `S ∈ᶠ F` means `F.sets S`. -/
def Mem (S : Sub I) (F : Filter I) : Prop := F.sets S
@[inherit_doc] notation:50 S " ∈ᶠ " F => Filter.Mem S F

/-- Two filters are equal when they have the same sets. -/
@[ext] theorem ext {F G : Filter I} (h : ∀ S, F.sets S ↔ G.sets S) : F = G := by
  cases F; cases G; simp only [Filter.mk.injEq]; exact Sub.ext h

/-- Members are never empty: if `S ∈ F` then `S` is inhabited. -/
theorem mem_nonempty {F : Filter I} {S : Sub I} (hS : F.sets S) : ∃ a, S a := by
  refine Classical.byContradiction (fun hcon => F.empty_not_mem ?_)
  have : S = empty := Sub.ext fun a => ⟨fun ha => (hcon ⟨a, ha⟩).elim, fun h => h.elim⟩
  exact this ▸ hS

/-- The order on filters: `F ≤ᶠ G` means `G` extends `F` (every set of `F` is a set of `G`). -/
def le (F G : Filter I) : Prop := ∀ ⦃S⦄, F.sets S → G.sets S
@[inherit_doc] infixl:50 " ≤ᶠ " => Filter.le

theorem le_refl (F : Filter I) : F ≤ᶠ F := fun _ h => h
theorem le_trans {F G H : Filter I} (h₁ : F ≤ᶠ G) (h₂ : G ≤ᶠ H) : F ≤ᶠ H := fun _ h => h₂ (h₁ h)
theorem le_antisymm {F G : Filter I} (h₁ : F ≤ᶠ G) (h₂ : G ≤ᶠ F) : F = G :=
  Filter.ext fun _ => ⟨fun h => h₁ h, fun h => h₂ h⟩

/-! ### Adjoining a set to a filter

If `Sᶜ ∉ F`, the filter `extend F S` generated by `F ∪ {S}` is proper and strictly above `F`
(it contains `S`).  Its members are the supersets of `A ∩ S` for `A ∈ F`. -/

/-- The filter generated by adjoining `S` to `F`: members are supersets of `A ∩ S`, `A ∈ F`. -/
def extendSets (F : Filter I) (S : Sub I) : Sub I → Prop :=
  fun T => ∃ A, F.sets A ∧ (A ∩ᵤ S) ⊆ₛ T

/-- `extendSets` is proper exactly when `Sᶜ ∉ F`: an empty `A ∩ S` means `A ⊆ Sᶜ`, i.e. `Sᶜ ∈ F`. -/
theorem extend_proper {F : Filter I} {S : Sub I} (hSc : ¬ F.sets Sᶜ) :
    ¬ extendSets F S empty := by
  rintro ⟨A, hA, hsub⟩
  -- A ∩ S ⊆ ∅ means A ⊆ Sᶜ, so Sᶜ ∈ F by up-closure, contradiction.
  exact hSc (F.up_closed hA (fun a ha hSa => hsub ⟨ha, hSa⟩))

/-- The extended filter (needs `Sᶜ ∉ F` for properness). -/
def extend (F : Filter I) (S : Sub I) (hSc : ¬ F.sets Sᶜ) : Filter I where
  sets := extendSets F S
  empty_not_mem := extend_proper hSc
  univ_mem := ⟨univ, F.univ_mem, fun _ _ => trivial⟩
  up_closed := fun ⟨A, hA, hsub⟩ hTU => ⟨A, hA, Sub.Subset.trans hsub hTU⟩
  inter_mem := by
    rintro T U ⟨A, hA, hAT⟩ ⟨B, hB, hBU⟩
    -- (A ∩ B) ∩ S ⊆ T ∩ U
    refine ⟨A ∩ᵤ B, F.inter_mem hA hB, fun a ha => ⟨hAT ⟨ha.1.1, ha.2⟩, hBU ⟨ha.1.2, ha.2⟩⟩⟩

/-- The extension extends `F`. -/
theorem le_extend {F : Filter I} {S : Sub I} (hSc : ¬ F.sets Sᶜ) : F ≤ᶠ extend F S hSc :=
  fun T hT => ⟨T, hT, fun _ ha => ha.1⟩

/-! ### The filter generated by a directed family (principal coideals)

§1.646 feeds the existence theorem a filter `F₀` of "principal coideals": for `I` = finite sets of
proper subobjects, the up-set `coideal i = {j | i ⊆ j}`.  Such up-sets are *directed* (the up-set of
`i ∪ i'` sits inside both) and nonempty, so the family `{ coideal i }` has the finite-intersection
property; the generated filter `{ S | ∃ i, coideal i ⊆ S }` is proper and is the `F₀` we extend to an
ultrafilter.  We package the construction abstractly: any directed, nonempty-valued family generates a
proper filter. -/

/-- A family `B : J → Sub I` is a **filter base**: each `B j` is nonempty and any two have a common
    sub-member (downward directed).  This is exactly the finite-intersection-property data §1.646 has
    for its principal coideals. -/
structure Base (I : Type u) (J : Type u) where
  /-- A distinguished index, so the family is nonempty (the generated filter contains `univ`). -/
  pt : J
  /-- The family of generating sets. -/
  set : J → Sub I
  /-- Each generator is nonempty (so the generated filter is proper). -/
  nonempty : ∀ j, ∃ a, set j a
  /-- Downward directed: two generators have a common sub-generator. -/
  directed : ∀ j k, ∃ l, set l ⊆ₛ set j ∧ set l ⊆ₛ set k

variable {J : Type u}

/-- The filter generated by a base: supersets of some generator. -/
def ofBase (B : Base I J) : Filter I where
  sets := fun S => ∃ j, B.set j ⊆ₛ S
  empty_not_mem := by
    rintro ⟨j, hj⟩
    obtain ⟨a, ha⟩ := B.nonempty j
    exact hj ha
  univ_mem := ⟨B.pt, fun _ _ => trivial⟩
  up_closed := fun ⟨j, hj⟩ hST => ⟨j, Sub.Subset.trans hj hST⟩
  inter_mem := by
    rintro S T ⟨j, hj⟩ ⟨k, hk⟩
    obtain ⟨l, hlj, hlk⟩ := B.directed j k
    exact ⟨l, fun a ha => ⟨hj (hlj ha), hk (hlk ha)⟩⟩

/-- Every generator belongs to the generated filter. -/
theorem set_mem_ofBase (B : Base I J) (j : J) : (ofBase B).sets (B.set j) :=
  ⟨j, Sub.Subset.refl _⟩

end Filter

/-- An ultrafilter: a proper filter that is *decisive* — for every set, it or its complement is in. -/
structure Ultrafilter (I : Type u) extends Filter I where
  /-- Decisiveness: every set or its complement is a member. -/
  decide : ∀ S, toFilter.sets S ∨ toFilter.sets Sᶜ

/-! ## Ultrafilter existence

We apply `WO.zorn` to the poset of proper filters extending a fixed `F₀`, ordered by `≤ᶠ`.
Every `≤ᶠ`-chain has an upper bound (the union filter, with `F₀` always thrown in so the empty chain is
bounded by `F₀` and properness/`univ` hold uniformly).  A maximal such filter is decisive, hence an
ultrafilter: if both `S` and `Sᶜ` were missing, adjoining one of them strictly enlarges it. -/

namespace Filter
variable {I : Type u}

/-- The poset of proper filters extending `F₀`. -/
abbrev Over (F₀ : Filter I) := {F : Filter I // F₀ ≤ᶠ F}

/-- Sets of the union of a chain `c` of filters extending `F₀`, with `F₀` always included so the
    empty chain is covered by `F₀`. -/
def chainUnionSets (F₀ : Filter I) (c : Over F₀ → Prop) : Sub I → Prop :=
  fun S => F₀.sets S ∨ ∃ G, c G ∧ G.val.sets S

/-- Comparability of the underlying filters of any two `c`-members (the form `chainUnion` consumes). -/
def OverChain (F₀ : Filter I) (c : Over F₀ → Prop) : Prop :=
  ∀ ⦃G⦄, c G → ∀ ⦃H⦄, c H → G.val ≤ᶠ H.val ∨ H.val ≤ᶠ G.val

/-- The union of a `≤ᶠ`-chain of filters `⊇ F₀` is again a proper filter `⊇ F₀`.  Directedness from the
    chain gives `inter_mem`; `F₀ ≤ᶠ` every chain member keeps everything inside one filter. -/
def chainUnion (F₀ : Filter I) (c : Over F₀ → Prop) (hc : OverChain F₀ c) : Filter I where
  sets := chainUnionSets F₀ c
  empty_not_mem := by
    rintro (h0 | ⟨G, _, hG⟩)
    · exact F₀.empty_not_mem h0
    · exact G.val.empty_not_mem hG
  univ_mem := Or.inl F₀.univ_mem
  up_closed := by
    rintro S T (h0 | ⟨G, hcG, hG⟩) hST
    · exact Or.inl (F₀.up_closed h0 hST)
    · exact Or.inr ⟨G, hcG, G.val.up_closed hG hST⟩
  inter_mem := by
    rintro S T hS hT
    -- Push both into a single chain member (or F₀), then intersect there.
    rcases hS with h0S | ⟨G, hcG, hGS⟩
    · rcases hT with h0T | ⟨H, hcH, hHT⟩
      · exact Or.inl (F₀.inter_mem h0S h0T)
      · exact Or.inr ⟨H, hcH, H.val.inter_mem (H.property h0S) hHT⟩
    · rcases hT with h0T | ⟨H, hcH, hHT⟩
      · exact Or.inr ⟨G, hcG, G.val.inter_mem hGS (G.property h0T)⟩
      · -- both in chain: compare G, H, intersect in the larger.
        rcases hc hcG hcH with hGH | hHG
        · exact Or.inr ⟨H, hcH, H.val.inter_mem (hGH hGS) hHT⟩
        · exact Or.inr ⟨G, hcG, G.val.inter_mem hGS (hHG hHT)⟩

theorem le_chainUnion (F₀ : Filter I) (c : Over F₀ → Prop) (hc : OverChain F₀ c) :
    F₀ ≤ᶠ chainUnion F₀ c hc := fun _ h => Or.inl h

theorem chainUnion_mem_of_mem {F₀ : Filter I} {c : Over F₀ → Prop}
    {hc : OverChain F₀ c} {G : Over F₀}
    (hcG : c G) {S : Sub I} (hGS : G.val.sets S) : (chainUnion F₀ c hc).sets S :=
  Or.inr ⟨G, hcG, hGS⟩

end Filter

/-- **Every proper filter extends to an ultrafilter** (`exists_ultrafilter_le`).  Apply Zorn to the
    proper filters `⊇ F₀`; a maximal one `M` is decisive, hence an ultrafilter `⊇ F₀`. -/
theorem exists_ultrafilter_le {I : Type u} (F₀ : Filter I) :
    ∃ U : Ultrafilter I, F₀ ≤ᶠ U.toFilter := by
  -- Poset P := filters extending F₀, ordered by ≤ᶠ.
  let leP : Filter.Over F₀ → Filter.Over F₀ → Prop := fun F G => F.val ≤ᶠ G.val
  have refl : ∀ a : Filter.Over F₀, leP a a := fun a => Filter.le_refl a.val
  have trans : ∀ {a b c : Filter.Over F₀}, leP a b → leP b c → leP a c :=
    fun {a b c} => Filter.le_trans (F := a.val) (G := b.val) (H := c.val)
  -- every leP-chain has an upper bound: the chainUnion filter.
  have chain_ub : ∀ c : Filter.Over F₀ → Prop, WO.IsChain leP c → ∃ m, WO.IsUB leP c m := by
    intro c hc
    have hc' : Filter.OverChain F₀ c := fun G hG H hH => hc hG hH
    let U := Filter.chainUnion F₀ c hc'
    have hUprop : F₀ ≤ᶠ U := Filter.le_chainUnion F₀ c hc'
    refine ⟨⟨U, hUprop⟩, ?_⟩
    intro G hcG S hGS
    exact Filter.chainUnion_mem_of_mem (hc := hc') hcG hGS
  obtain ⟨M, hMmax⟩ := WO.zorn leP refl @trans chain_ub
    ⟨⟨F₀, Filter.le_refl F₀⟩⟩
  -- M is decisive: for each S, if Sᶜ ∉ M then S ∈ M (else extend by S contradicts maximality).
  refine ⟨⟨M.val, ?_⟩, M.property⟩
  intro S
  by_cases hSc : M.val.sets Sᶜ
  · exact Or.inr hSc
  · refine Or.inl ?_
    -- extend M.val by S: strictly larger proper filter ⊇ F₀, so = M by maximality, so S ∈ M.
    let E := Filter.extend M.val S hSc
    have hEprop : F₀ ≤ᶠ E := Filter.le_trans M.property (Filter.le_extend hSc)
    have hME : leP M ⟨E, hEprop⟩ := Filter.le_extend hSc
    have hEM : leP ⟨E, hEprop⟩ M := hMmax ⟨E, hEprop⟩ hME
    exact hEM ⟨univ, M.val.univ_mem, fun _ ha => ha.2⟩

/-! ## Ultrafilter lemmas for §1.646

The consumer-facing facts the ultrapower representation `Tᶠ` uses. -/

namespace Ultrafilter
variable {I : Type u}

/-- Membership in an ultrafilter. -/
def Mem (S : Sub I) (U : Ultrafilter I) : Prop := U.toFilter.sets S

/-- An ultrafilter contains no empty set; in particular not both `S` and `Sᶜ`. -/
theorem not_mem_and_compl (U : Ultrafilter I) (S : Sub I) :
    ¬ (U.toFilter.sets S ∧ U.toFilter.sets Sᶜ) := by
  rintro ⟨hS, hSc⟩
  -- S ∩ Sᶜ = ∅ ∈ U, contradicting properness.
  have : U.toFilter.sets (S ∩ᵤ Sᶜ) := U.toFilter.inter_mem hS hSc
  have he : (S ∩ᵤ Sᶜ) = empty := Sub.ext fun a => ⟨fun h => h.2 h.1, fun h => h.elim⟩
  exact U.toFilter.empty_not_mem (he ▸ this)

/-- Decisiveness as an exclusive disjunction: exactly one of `S`, `Sᶜ` belongs. -/
theorem mem_iff_compl_not_mem (U : Ultrafilter I) (S : Sub I) :
    U.toFilter.sets S ↔ ¬ U.toFilter.sets Sᶜ := by
  constructor
  · intro hS hSc; exact not_mem_and_compl U S ⟨hS, hSc⟩
  · intro hSc; rcases U.decide S with h | h
    · exact h
    · exact absurd h hSc

/-- Finite intersection: closure under binary `∩` (and hence all finite meets). -/
theorem inter_mem' (U : Ultrafilter I) {S T : Sub I} (hS : U.toFilter.sets S)
    (hT : U.toFilter.sets T) : U.toFilter.sets (S ∩ᵤ T) := U.toFilter.inter_mem hS hT

/-- Upward closure. -/
theorem up_closed' (U : Ultrafilter I) {S T : Sub I} (hS : U.toFilter.sets S) (hST : S ⊆ₛ T) :
    U.toFilter.sets T := U.toFilter.up_closed hS hST

/-- Members are inhabited. -/
theorem mem_nonempty (U : Ultrafilter I) {S : Sub I} (hS : U.toFilter.sets S) : ∃ a, S a :=
  Filter.mem_nonempty hS

/-- If a member splits as `S = S₁ ∪ S₂` (i.e. `Sᶜ = S₁ᶜ ∩ S₂ᶜ`) then the ultrafilter picks a side:
    whenever `Sᶜ ∉ U` and `S₁ᶜ ∩ S₂ᶜ ⊆ Sᶜ`, one of `S₁`, `S₂` is in `U`.  This is the prime-ideal
    behaviour the §1.646 representation uses to route each index decision to one branch. -/
theorem mem_of_union {U : Ultrafilter I} {S₁ S₂ : Sub I}
    (hU : U.toFilter.sets (fun a => S₁ a ∨ S₂ a)) : U.toFilter.sets S₁ ∨ U.toFilter.sets S₂ := by
  -- if neither S₁ nor S₂ is in U, both complements are, so (S₁∪S₂)ᶜ = S₁ᶜ ∩ S₂ᶜ ∈ U — contradiction.
  refine Classical.byContradiction (fun hcon => ?_)
  have h1 : ¬ U.toFilter.sets S₁ := fun h => hcon (Or.inl h)
  have h2 : ¬ U.toFilter.sets S₂ := fun h => hcon (Or.inr h)
  have hc1 : U.toFilter.sets S₁ᶜ := (U.decide S₁).resolve_left h1
  have hc2 : U.toFilter.sets S₂ᶜ := (U.decide S₂).resolve_left h2
  have hcap : U.toFilter.sets (S₁ᶜ ∩ᵤ S₂ᶜ) := U.toFilter.inter_mem hc1 hc2
  -- S₁ᶜ ∩ S₂ᶜ = (S₁ ∪ S₂)ᶜ
  have he : (S₁ᶜ ∩ᵤ S₂ᶜ) = (fun a => S₁ a ∨ S₂ a)ᶜ :=
    Sub.ext fun a => ⟨fun ⟨hn1, hn2⟩ ho => ho.elim hn1 hn2,
      fun hno => ⟨fun hh => hno (Or.inl hh), fun hh => hno (Or.inr hh)⟩⟩
  rw [he] at hcap
  exact not_mem_and_compl U (fun a => S₁ a ∨ S₂ a) ⟨hU, hcap⟩

end Ultrafilter

/-- **§1.646 entry point.**  Every filter base (a nonempty downward-directed family of nonempty sets —
    e.g. the principal coideals) is contained in an ultrafilter: each generator of the base is a member
    of the resulting ultrafilter.  This is exactly "an ultrafilter `F ⊇ principal coideals". -/
theorem exists_ultrafilter_of_base {I J : Type u} (B : Filter.Base I J) :
    ∃ U : Ultrafilter I, ∀ j, U.toFilter.sets (B.set j) := by
  obtain ⟨U, hU⟩ := exists_ultrafilter_le (Filter.ofBase B)
  exact ⟨U, fun j => hU (Filter.set_mem_ofBase B j)⟩

end Freyd.UF
