/-
  Mathlib-free ultrafilter infrastructure for §1.646.

  ## Why this file exists

  §1.646's representation needs: `I` = the (directed) index of finite sets of proper subobjects, a
  proper filter `F₀` on `I` of "principal coideals", and an ULTRAFILTER `F ⊇ F₀`, so the ultrapower
  `Tᶠ` is faithful (S1_64.lean:113-124).  Freyd treats ultrafilters as ambient set theory and uses
  choice freely; mathlib supplies them but the repo is deliberately mathlib-free.

  This file builds, from `Classical.choice` ALONE:

  * `Filter I`              — a proper filter (sets-of-subsets style, via `Sub I = I → Prop`).
  * `Ultrafilter I`         — a maximal proper filter; equivalently `∀ S, S ∈ F ∨ Sᶜ ∈ F`.
  * `exists_ultrafilter_le` — every proper filter extends to an ultrafilter (Zorn / Bourbaki–Witt).

  ## Method

  The repo has no reusable Zorn lemma, so we develop a MINIMAL Zorn's lemma inline by the same
  Bourbaki–Witt tower fixpoint used in `Freyd/WellOrdering.lean`: a choice function picks a strict
  upper bound whenever one exists; towers of iterated picks form a chain; their union is a chain with
  an upper bound `u`; `u` admits no strict upper bound, i.e. is maximal.  Specialised to the poset of
  proper filters `⊇ F₀` (chains closed under union of filters), the maximal element is an ultrafilter.
-/
import Freyd.S1_543_WellOrdering

namespace Freyd.UF

universe u

/-\! ## The boolean operations a filter needs

`Sub I = I → Prop` (a subset as a predicate) with `⊆ₛ`, `ext`, `Subset.refl`, `Subset.trans` comes
from `Freyd.Sub` (§1.543); only the operations specific to filters are here.  Their notations stay
local to this file — a global `ᶜ` would clash with the Heyting complement. -/

variable {I : Type u}

/-- The whole index set. -/
def univ : Sub I := fun _ => True
/-- The empty set. -/
def empty : Sub I := fun _ => False
/-- Complement. -/
def compl (s : Sub I) : Sub I := fun a => ¬ s a
@[inherit_doc] postfix:max "ᶜ" => compl
/-- Binary intersection. -/
def inter (s t : Sub I) : Sub I := fun a => s a ∧ t a
@[inherit_doc] infixl:70 " ∩ᵤ " => inter

theorem mem_univ (a : I) : univ a := trivial
theorem inter_subset_left {s t : Sub I} : s ∩ᵤ t ⊆ₛ s := fun _ h => h.1
theorem inter_subset_right {s t : Sub I} : s ∩ᵤ t ⊆ₛ t := fun _ h => h.2

/-\! ## Filters and ultrafilters -/

/-- A proper filter on `I`. -/
structure Filter (I : Type u) where
  /-- The sets belonging to the filter. -/
  sets : Sub I → Prop
  /-- The filter is proper: the empty set is not a member. -/
  empty_not_mem : ¬ sets empty
  /-- The whole set is a member. -/
  univ_mem : sets univ
  /-- Upward closed: a superset of a member is a member. -/
  up_closed : ∀ {s t}, sets s → s ⊆ₛ t → sets t
  /-- Closed under binary intersection. -/
  inter_mem : ∀ {s t}, sets s → sets t → sets (s ∩ᵤ t)

namespace Filter
variable {I : Type u}

/-- Membership: `S ∈ᶠ F` means `F.sets S`. -/
def Mem (S : Sub I) (F : Filter I) : Prop := F.sets S
@[inherit_doc] notation:50 S " ∈ᶠ " F => Filter.Mem S F

/-- Two filters are equal when they have the same sets. -/
@[ext] theorem ext {F G : Filter I} (h : ∀ S, F.sets S ↔ G.sets S) : F = G := by
  cases F; cases G; simp only [Filter.mk.injEq]; exact Sub.ext h

/-- Members are never empty: if `S ∈ F` then `S` is inhabited. -/
theorem mem_nonempty {F : Filter I} {S : Sub I} (hS : F.sets S) : ∃ a, S a := by
  refine Classical.byContradiction (fun hcon => F.empty_not_mem ?_)
  have : S = empty := Sub.ext fun a => ⟨fun ha => (hcon ⟨a, ha⟩).elim, fun h => h.elim⟩
  exact this ▸ hS

/-- The order on filters: `F ≤ᶠ G` means `G` extends `F` (every set of `F` is a set of `G`). -/
def le (F G : Filter I) : Prop := ∀ ⦃S⦄, F.sets S → G.sets S
@[inherit_doc] infixl:50 " ≤ᶠ " => Filter.le

theorem le_refl (F : Filter I) : F ≤ᶠ F := fun _ h => h
theorem le_trans {F G H : Filter I} (h₁ : F ≤ᶠ G) (h₂ : G ≤ᶠ H) : F ≤ᶠ H := fun _ h => h₂ (h₁ h)
theorem le_antisymm {F G : Filter I} (h₁ : F ≤ᶠ G) (h₂ : G ≤ᶠ F) : F = G :=
  Filter.ext fun _ => ⟨fun h => h₁ h, fun h => h₂ h⟩

/-! ### Adjoining a set to a filter

If `Sᶜ ∉ F`, the filter `extend F S` generated by `F ∪ {S}` is proper and strictly above `F`
(it contains `S`).  Its members are the supersets of `A ∩ S` for `A ∈ F`. -/

/-- The filter generated by adjoining `S` to `F`: members are supersets of `A ∩ S`, `A ∈ F`. -/
def extendSets (F : Filter I) (S : Sub I) : Sub I → Prop :=
  fun T => ∃ A, F.sets A ∧ (A ∩ᵤ S) ⊆ₛ T

/-- `extendSets` is proper exactly when `Sᶜ ∉ F`: an empty `A ∩ S` means `A ⊆ Sᶜ`, i.e. `Sᶜ ∈ F`. -/
theorem extend_proper {F : Filter I} {S : Sub I} (hSc : ¬ F.sets Sᶜ) :
    ¬ extendSets F S empty := by
  rintro ⟨A, hA, hsub⟩
  -- A ∩ S ⊆ ∅ means A ⊆ Sᶜ, so Sᶜ ∈ F by up-closure, contradiction.
  exact hSc (F.up_closed hA (fun a ha hSa => hsub ⟨ha, hSa⟩))

/-- The extended filter (needs `Sᶜ ∉ F` for properness). -/
def extend (F : Filter I) (S : Sub I) (hSc : ¬ F.sets Sᶜ) : Filter I where
  sets := extendSets F S
  empty_not_mem := extend_proper hSc
  univ_mem := ⟨univ, F.univ_mem, fun _ _ => trivial⟩
  up_closed := fun ⟨A, hA, hsub⟩ hTU => ⟨A, hA, Sub.Subset.trans hsub hTU⟩
  inter_mem := by
    rintro T U ⟨A, hA, hAT⟩ ⟨B, hB, hBU⟩
    -- (A ∩ B) ∩ S ⊆ T ∩ U
    refine ⟨A ∩ᵤ B, F.inter_mem hA hB, fun a ha => ⟨hAT ⟨ha.1.1, ha.2⟩, hBU ⟨ha.1.2, ha.2⟩⟩⟩

/-- The extension extends `F`. -/
theorem le_extend {F : Filter I} {S : Sub I} (hSc : ¬ F.sets Sᶜ) : F ≤ᶠ extend F S hSc :=
  fun T hT => ⟨T, hT, fun _ ha => ha.1⟩

/-! ### The filter generated by a directed family (principal coideals)

§1.646 feeds the existence theorem a filter `F₀` of "principal coideals": for `I` = finite sets of
proper subobjects, the up-set `coideal i = {j | i ⊆ j}`.  Such up-sets are *directed* (the up-set of
`i ∪ i'` sits inside both) and nonempty, so the family `{ coideal i }` has the finite-intersection
property; the generated filter `{ S | ∃ i, coideal i ⊆ S }` is proper and is the `F₀` we extend to an
ultrafilter.  We package the construction abstractly: any directed, nonempty-valued family generates a
proper filter. -/

/-- A family `B : J → Sub I` is a **filter base**: each `B j` is nonempty and any two have a common
    sub-member (downward directed).  This is exactly the finite-intersection-property data §1.646 has
    for its principal coideals. -/
structure Base (I : Type u) (J : Type u) where
  /-- A distinguished index, so the family is nonempty (the generated filter contains `univ`). -/
  pt : J
  /-- The family of generating sets. -/
  set : J → Sub I
  /-- Each generator is nonempty (so the generated filter is proper). -/
  nonempty : ∀ j, ∃ a, set j a
  /-- Downward directed: two generators have a common sub-generator. -/
  directed : ∀ j k, ∃ l, set l ⊆ₛ set j ∧ set l ⊆ₛ set k

variable {J : Type u}

/-- The filter generated by a base: supersets of some generator. -/
def ofBase (B : Base I J) : Filter I where
  sets := fun S => ∃ j, B.set j ⊆ₛ S
  empty_not_mem := by
    rintro ⟨j, hj⟩
    obtain ⟨a, ha⟩ := B.nonempty j
    exact hj ha
  univ_mem := ⟨B.pt, fun _ _ => trivial⟩
  up_closed := fun ⟨j, hj⟩ hST => ⟨j, Sub.Subset.trans hj hST⟩
  inter_mem := by
    rintro S T ⟨j, hj⟩ ⟨k, hk⟩
    obtain ⟨l, hlj, hlk⟩ := B.directed j k
    exact ⟨l, fun a ha => ⟨hj (hlj ha), hk (hlk ha)⟩⟩

/-- Every generator belongs to the generated filter. -/
theorem set_mem_ofBase (B : Base I J) (j : J) : (ofBase B).sets (B.set j) :=
  ⟨j, Sub.Subset.refl _⟩

end Filter

/-- An ultrafilter: a proper filter that is *decisive* — for every set, it or its complement is in. -/
structure Ultrafilter (I : Type u) extends Filter I where
  /-- Decisiveness: every set or its complement is a member. -/
  decide : ∀ S, toFilter.sets S ∨ toFilter.sets Sᶜ

/-! ## A minimal Zorn's lemma (Bourbaki–Witt tower)

We prove the chain form of Zorn for an arbitrary preorder, from `Classical.choice`, by the same tower
fixpoint as `WellOrdering`.  Fix a choice function `g` that, given `p`, returns a *strict* upper bound
of `p` whenever one exists (else `p` itself).  Towers are collections built from a base by `g` and by
unions; they are `le`-chains; the union of all towers is a chain, its upper bound is maximal. -/

section Zorn

variable {P : Type u} (le : P → P → Prop)

/-- `p` is `le`-below everything in the collection `c` that it is comparable to — used to phrase chains.
    A collection `c : P → Prop` is a **chain** when any two of its members are `le`-comparable. -/
def Chain (c : P → Prop) : Prop := ∀ ⦃a⦄, c a → ∀ ⦃b⦄, c b → le a b ∨ le b a

/-- `m` is an upper bound of `c`. -/
def IsUB (c : P → Prop) (m : P) : Prop := ∀ ⦃a⦄, c a → le a m

variable (refl : ∀ a, le a a) (trans : ∀ {a b c}, le a b → le b c → le a c)

/-- `m` is maximal: nothing is strictly above it. -/
def IsMax (m : P) : Prop := ∀ a, le m a → le a m

end Zorn

namespace Zorn
open Classical
variable {P : Type u} {le : P → P → Prop}

/-- The choice function: if `p` has a *strict* upper bound (some `q` with `le p q` but `¬ le q p`),
    return one; otherwise return `p`.  "`p` is maximal" is exactly "`g p = p` returns no strict step",
    captured by `g_spec`. -/
noncomputable def g (le : P → P → Prop) (p : P) : P :=
  if h : ∃ q, le p q ∧ ¬ le q p then Classical.choose h else p

/-- If `p` has a strict upper bound, `g le p` is one (`le p (g p)` and `¬ le (g p) p`). -/
theorem g_strict {p : P} (h : ∃ q, le p q ∧ ¬ le q p) :
    le p (g le p) ∧ ¬ le (g le p) p := by
  unfold g; rw [dif_pos h]; exact Classical.choose_spec h

/-- If `p` is maximal (no strict upper bound) then `g le p = p`. -/
theorem g_eq_of_max {p : P} (h : ¬ ∃ q, le p q ∧ ¬ le q p) : g le p = p := by
  unfold g; rw [dif_neg h]

/-- `g` is extensive *given* reflexivity: `le p (g le p)`. -/
theorem le_g (refl : ∀ a, le a a) (p : P) : le p (g le p) := by
  by_cases h : ∃ q, le p q ∧ ¬ le q p
  · exact (g_strict h).1
  · rw [g_eq_of_max h]; exact refl p

/-! ### The element-tower

Fix a preorder `(le, refl, trans)` and an upper-bound operator `ub : (P → Prop) → P` returning, for
every collection, some element above all members that lie in a tower (we only ever apply `ub` to
towers, which we prove are chains).  A **tower** is a collection of points built from the empty
collection by:
  * `step c`: adjoin `g (ub c)` — the strict-successor of the current ceiling, and
  * unions of sub-families.
Mirroring `WellOrdering`, towers are pairwise `⊆`-comparable, hence each is a chain, so `ub` genuinely
bounds it; the union of all towers is `g`-closed at its own ceiling, forcing that ceiling to be a
fixpoint of `g`, i.e. a maximal element. -/

variable (le) (ub : (P → Prop) → P)

/-- Successor of a collection: adjoin the strict-successor of its ceiling. -/
def csucc (c : P → Prop) : P → Prop := fun x => c x ∨ x = g le (ub c)

theorem csub_csucc (c : P → Prop) : c ⊆ₛ csucc le ub c := fun _ h => Or.inl h
theorem mem_csucc_self (c : P → Prop) : csucc le ub c (g le (ub c)) := Or.inr rfl

variable {le ub}

/-- A **tower** for `(le, ub)`. -/
inductive Tower : (P → Prop) → Prop
  | step (c : P → Prop) : Tower c → Tower (csucc le ub c)
  | sUnion (Q : (P → Prop) → Prop) (h : ∀ c, Q c → Tower c) :
      Tower (fun x => ∃ c : P → Prop, Q c ∧ c x)

/-- The empty collection is a tower (empty union). -/
theorem Tower.empty : Tower (le := le) (ub := ub) (fun _ => False) := by
  have h := Tower.sUnion (le := le) (ub := ub) (fun _ => False) (fun c hc => hc.elim)
  have e : (fun x : P => ∃ c : P → Prop, (fun _ => False) c ∧ c x) = (fun _ : P => False) :=
    funext fun x => propext ⟨fun ⟨_, hf, _⟩ => hf.elim, fun hf => hf.elim⟩
  rwa [e] at h

/-! #### Comparability (Bourbaki–Witt chain lemma), ported from `WellOrdering`. -/

/-- `c` is narrow: no tower sits strictly between any `s ⊆ c` and its successor. -/
def Narrow (c : P → Prop) : Prop :=
  ∀ s, Tower (le := le) (ub := ub) s → s ⊆ₛ c → s = c ∨ csucc le ub s ⊆ₛ c

/-- A narrow tower is comparable with every tower. -/
theorem compare_of_narrow {c : P → Prop} (hcN : Narrow (le := le) (ub := ub) c) :
    ∀ {s}, Tower (le := le) (ub := ub) s → s ⊆ₛ c ∨ c ⊆ₛ s := by
  intro s hs
  induction hs with
  | step t ht ih =>
    rcases ih with htc | hct
    · rcases hcN t ht htc with heq | hsc
      · exact Or.inr (heq ▸ csub_csucc le ub t)
      · exact Or.inl hsc
    · exact Or.inr (Sub.Subset.trans hct (csub_csucc le ub t))
  | sUnion Q hQ ih =>
    by_cases hall : ∀ s, Q s → s ⊆ₛ c
    · exact Or.inl (fun x ⟨s, hQs, hsx⟩ => hall s hQs hsx)
    · have : ∃ s, Q s ∧ ¬ s ⊆ₛ c := by
        refine Classical.byContradiction (fun hcon => hall (fun s hQs => ?_))
        exact Classical.byContradiction (fun hns => hcon ⟨s, hQs, hns⟩)
      obtain ⟨s, hQs, hns⟩ := this
      rcases ih s hQs with hsc | hcs
      · exact absurd hsc hns
      · exact Or.inr (fun x hcx => ⟨s, hQs, hcs hcx⟩)

/-- Every tower is narrow. -/
theorem Tower.narrow :
    ∀ {c}, Tower (le := le) (ub := ub) c → Narrow (le := le) (ub := ub) c := by
  intro c hc
  induction hc with
  | step t ht iht =>
    intro s hs hsc
    rcases compare_of_narrow iht hs with hst | hts
    · rcases iht s hs hst with heq | hsub
      · exact Or.inr (heq ▸ Sub.Subset.refl _)
      · exact Or.inr (Sub.Subset.trans hsub (csub_csucc le ub t))
    · by_cases hg : s (g le (ub t))
      · refine Or.inl (Sub.Subset.antisymm hsc (fun x hx => ?_))
        rcases hx with hxt | rfl
        · exact hts hxt
        · exact hg
      · have hstt : s ⊆ₛ t := by
          intro x hx
          rcases hsc hx with hxt | rfl
          · exact hxt
          · exact absurd hx hg
        have : s = t := Sub.Subset.antisymm hstt hts
        exact Or.inr (this ▸ Sub.Subset.refl _)
  | sUnion Q hQ ihQ =>
    intro s hs hsc
    by_cases hsc' : s = (fun x => ∃ t : P → Prop, Q t ∧ t x)
    · exact Or.inl hsc'
    · refine Or.inr ?_
      have hex : ∃ p, Q p ∧ ¬ p ⊆ₛ s := by
        refine Classical.byContradiction (fun hcon => hsc' ?_)
        have hall : ∀ p, Q p → p ⊆ₛ s := by
          intro p hQp
          refine Classical.byContradiction (fun hnp => hcon ⟨p, hQp, hnp⟩)
        exact Sub.Subset.antisymm hsc (fun x ⟨p, hQp, hpx⟩ => hall p hQp hpx)
      obtain ⟨p, hQp, hnp⟩ := hex
      rcases compare_of_narrow (ihQ p hQp) hs with hsp | hps
      · rcases (ihQ p hQp) s hs hsp with heq | hsub
        · exact absurd (heq ▸ Sub.Subset.refl p) hnp
        · exact fun x hx => ⟨p, hQp, hsub hx⟩
      · exact absurd hps hnp

/-- **Chain lemma**: any two towers are `⊆`-comparable. -/
theorem tower_compare {s t : P → Prop} (hs : Tower (le := le) (ub := ub) s)
    (ht : Tower (le := le) (ub := ub) t) : s ⊆ₛ t ∨ t ⊆ₛ s :=
  compare_of_narrow ht.narrow hs

/-! #### Towers are `le`-chains and `ub` bounds them

We now bring in the preorder data and the defining property of `ub`: it is an upper bound of every
tower (which we simultaneously prove is a chain).  These give the fixpoint. -/

variable (hrefl : ∀ a, le a a) (htrans : ∀ {a b c}, le a b → le b c → le a c)
  (hub : ∀ c, Chain le c → IsUB le c (ub c))

include hrefl htrans hub in
/-- Every tower is a `le`-chain.  Uses `hub` only on chains (sub-towers proved chains by the IH). -/
theorem tower_chain : ∀ {c}, Tower (le := le) (ub := ub) c → Chain le c := by
  intro c hc
  induction hc with
  | step t ht iht =>
    -- new ceiling m = g (ub t); everything in t is ≤ ub t ≤ m, so comparable to m and to each other.
    have hm : le (ub t) (g le (ub t)) := le_g hrefl _
    intro a ha b hb
    rcases ha with hat | rfl
    · rcases hb with hbt | rfl
      · exact iht hat hbt
      · exact Or.inl (htrans (hub t iht hat) hm)
    · rcases hb with hbt | rfl
      · exact Or.inr (htrans (hub t iht hbt) hm)
      · exact Or.inl (hrefl _)
  | sUnion Q hQ ihQ =>
    intro a ⟨ca, hQca, hca⟩ b ⟨cb, hQcb, hcb⟩
    -- ca, cb towers in the family; comparable, so both members of the larger chain.
    rcases tower_compare (hQ ca hQca) (hQ cb hQcb) with hab | hba
    · exact ihQ cb hQcb (hab hca) hcb
    · exact ihQ ca hQca hca (hba hcb)

/-! #### The maximal element (Bourbaki–Witt fixpoint) -/

/-- The union of all towers. -/
def bigU : P → Prop := fun x => ∃ t : P → Prop, Tower (le := le) (ub := ub) t ∧ t x

/-- Any tower is contained in `bigU`. -/
theorem subset_bigU {t : P → Prop} (ht : Tower (le := le) (ub := ub) t) :
    t ⊆ₛ bigU (le := le) (ub := ub) := fun _ hx => ⟨t, ht, hx⟩

include hrefl htrans hub in
/-- **Maximal element via Bourbaki–Witt.**  `m := ub bigU` is `le`-maximal: any strict step `g le m`
    lands back inside `bigU` (its successor is a tower) and so is `≤ m`, contradicting strictness. -/
theorem ub_bigU_isMax : IsMax le (ub (bigU (le := le) (ub := ub))) := by
  -- g le (ub bigU) ∈ bigU, since csucc bigU is a tower hence ⊆ bigU
  have hsucc : Tower (le := le) (ub := ub) (csucc le ub (bigU (le := le) (ub := ub))) :=
    Tower.step _ (Tower.sUnion (le := le) (ub := ub) (Tower (le := le) (ub := ub)) (fun _ h => h))
  have hmem : bigU (le := le) (ub := ub) (g le (ub (bigU (le := le) (ub := ub)))) :=
    subset_bigU hsucc (mem_csucc_self le ub _)
  -- chain ⟹ g le (ub bigU) ≤ ub bigU
  have hchain : Chain le (bigU (le := le) (ub := ub)) := tower_chain hrefl @htrans hub
    (Tower.sUnion (le := le) (ub := ub) (Tower (le := le) (ub := ub)) (fun _ h => h))
  have hle : le (g le (ub (bigU (le := le) (ub := ub)))) (ub (bigU (le := le) (ub := ub))) :=
    hub _ hchain hmem
  -- if ub bigU had a strict upper bound, g le (ub bigU) would be one with ¬ le _ (ub bigU)
  intro a hma
  refine Classical.byContradiction (fun hcon => ?_)
  exact (g_strict ⟨a, hma, hcon⟩).2 hle

end Zorn

/-! ### Zorn's lemma, packaged

`exists_maximal`: a preorder in which every chain has an upper bound has a maximal element, provided the
type is nonempty (the empty chain needs a bound, supplied by any point).  We feed `ub` from the
chain-bound hypothesis via `Classical.choice`. -/

open Zorn in
/-- **Zorn's lemma (chain form), mathlib-free.**  If `le` is a preorder on `P` and every `le`-chain
    has an upper bound, then `P` has a `le`-maximal element. -/
theorem exists_maximal {P : Type u} (le : P → P → Prop)
    (refl : ∀ a, le a a) (trans : ∀ {a b c}, le a b → le b c → le a c)
    (chain_ub : ∀ c : P → Prop, Chain le c → ∃ m, IsUB le c m) :
    ∃ m, IsMax le m := by
  -- choose an upper bound for every chain (default to the empty-chain bound otherwise)
  have hbnd : ∀ c : P → Prop, ∃ m, Chain le c → IsUB le c m := by
    intro c
    by_cases hch : Chain le c
    · obtain ⟨m, hm⟩ := chain_ub c hch; exact ⟨m, fun _ => hm⟩
    · obtain ⟨m, hm⟩ := chain_ub (fun _ => False) (fun _ h => h.elim)
      exact ⟨m, fun hc => absurd hc hch⟩
  let ub : (P → Prop) → P := fun c => Classical.choose (hbnd c)
  have hub : ∀ c, Chain le c → IsUB le c (ub c) :=
    fun c hc => Classical.choose_spec (hbnd c) hc
  exact ⟨ub (bigU (le := le) (ub := ub)), ub_bigU_isMax refl @trans hub⟩

/-! ## Ultrafilter existence

We apply `exists_maximal` to the poset of proper filters extending a fixed `F₀`, ordered by `≤ᶠ`.
Every `≤ᶠ`-chain has an upper bound (the union filter, with `F₀` always thrown in so the empty chain is
bounded by `F₀` and properness/`univ` hold uniformly).  A maximal such filter is decisive, hence an
ultrafilter: if both `S` and `Sᶜ` were missing, adjoining one of them strictly enlarges it. -/

namespace Filter
variable {I : Type u}

/-- The poset of proper filters extending `F₀`. -/
abbrev Over (F₀ : Filter I) := {F : Filter I // F₀ ≤ᶠ F}

/-- Sets of the union of a chain `c` of filters extending `F₀`, with `F₀` always included so the
    empty chain is covered by `F₀`. -/
def chainUnionSets (F₀ : Filter I) (c : Over F₀ → Prop) : Sub I → Prop :=
  fun S => F₀.sets S ∨ ∃ G, c G ∧ G.val.sets S

/-- Comparability of the underlying filters of any two `c`-members (the form `chainUnion` consumes). -/
def OverChain (F₀ : Filter I) (c : Over F₀ → Prop) : Prop :=
  ∀ ⦃G⦄, c G → ∀ ⦃H⦄, c H → G.val ≤ᶠ H.val ∨ H.val ≤ᶠ G.val

/-- The union of a `≤ᶠ`-chain of filters `⊇ F₀` is again a proper filter `⊇ F₀`.  Directedness from the
    chain gives `inter_mem`; `F₀ ≤ᶠ` every chain member keeps everything inside one filter. -/
def chainUnion (F₀ : Filter I) (c : Over F₀ → Prop) (hc : OverChain F₀ c) : Filter I where
  sets := chainUnionSets F₀ c
  empty_not_mem := by
    rintro (h0 | ⟨G, _, hG⟩)
    · exact F₀.empty_not_mem h0
    · exact G.val.empty_not_mem hG
  univ_mem := Or.inl F₀.univ_mem
  up_closed := by
    rintro S T (h0 | ⟨G, hcG, hG⟩) hST
    · exact Or.inl (F₀.up_closed h0 hST)
    · exact Or.inr ⟨G, hcG, G.val.up_closed hG hST⟩
  inter_mem := by
    rintro S T hS hT
    -- Push both into a single chain member (or F₀), then intersect there.
    rcases hS with h0S | ⟨G, hcG, hGS⟩
    · rcases hT with h0T | ⟨H, hcH, hHT⟩
      · exact Or.inl (F₀.inter_mem h0S h0T)
      · exact Or.inr ⟨H, hcH, H.val.inter_mem (H.property h0S) hHT⟩
    · rcases hT with h0T | ⟨H, hcH, hHT⟩
      · exact Or.inr ⟨G, hcG, G.val.inter_mem hGS (G.property h0T)⟩
      · -- both in chain: compare G, H, intersect in the larger.
        rcases hc hcG hcH with hGH | hHG
        · exact Or.inr ⟨H, hcH, H.val.inter_mem (hGH hGS) hHT⟩
        · exact Or.inr ⟨G, hcG, G.val.inter_mem hGS (hHG hHT)⟩

theorem le_chainUnion (F₀ : Filter I) (c : Over F₀ → Prop) (hc : OverChain F₀ c) :
    F₀ ≤ᶠ chainUnion F₀ c hc := fun _ h => Or.inl h

theorem chainUnion_mem_of_mem {F₀ : Filter I} {c : Over F₀ → Prop}
    {hc : OverChain F₀ c} {G : Over F₀}
    (hcG : c G) {S : Sub I} (hGS : G.val.sets S) : (chainUnion F₀ c hc).sets S :=
  Or.inr ⟨G, hcG, hGS⟩

end Filter

/-- **Every proper filter extends to an ultrafilter** (`exists_ultrafilter_le`).  Apply Zorn to the
    proper filters `⊇ F₀`; a maximal one `M` is decisive, hence an ultrafilter `⊇ F₀`. -/
theorem exists_ultrafilter_le {I : Type u} (F₀ : Filter I) :
    ∃ U : Ultrafilter I, F₀ ≤ᶠ U.toFilter := by
  -- Poset P := filters extending F₀, ordered by ≤ᶠ.
  let leP : Filter.Over F₀ → Filter.Over F₀ → Prop := fun F G => F.val ≤ᶠ G.val
  have refl : ∀ a : Filter.Over F₀, leP a a := fun a => Filter.le_refl a.val
  have trans : ∀ {a b c : Filter.Over F₀}, leP a b → leP b c → leP a c :=
    fun {a b c} => Filter.le_trans (F := a.val) (G := b.val) (H := c.val)
  -- every leP-chain has an upper bound: the chainUnion filter.
  have chain_ub : ∀ c : Filter.Over F₀ → Prop, Chain leP c → ∃ m, IsUB leP c m := by
    intro c hc
    have hc' : Filter.OverChain F₀ c := fun G hG H hH => hc hG hH
    let U := Filter.chainUnion F₀ c hc'
    have hUprop : F₀ ≤ᶠ U := Filter.le_chainUnion F₀ c hc'
    refine ⟨⟨U, hUprop⟩, ?_⟩
    intro G hcG S hGS
    exact Filter.chainUnion_mem_of_mem (hc := hc') hcG hGS
  obtain ⟨M, hMmax⟩ := exists_maximal leP refl @trans chain_ub
  -- M is decisive: for each S, if Sᶜ ∉ M then S ∈ M (else extend by S contradicts maximality).
  refine ⟨⟨M.val, ?_⟩, M.property⟩
  intro S
  by_cases hSc : M.val.sets Sᶜ
  · exact Or.inr hSc
  · refine Or.inl ?_
    -- extend M.val by S: strictly larger proper filter ⊇ F₀, so = M by maximality, so S ∈ M.
    let E := Filter.extend M.val S hSc
    have hEprop : F₀ ≤ᶠ E := Filter.le_trans M.property (Filter.le_extend hSc)
    have hME : leP M ⟨E, hEprop⟩ := Filter.le_extend hSc
    have hEM : leP ⟨E, hEprop⟩ M := hMmax ⟨E, hEprop⟩ hME
    exact hEM ⟨univ, M.val.univ_mem, fun _ ha => ha.2⟩

/-! ## Ultrafilter lemmas for §1.646

The consumer-facing facts the ultrapower representation `Tᶠ` uses. -/

namespace Ultrafilter
variable {I : Type u}

/-- Membership in an ultrafilter. -/
def Mem (S : Sub I) (U : Ultrafilter I) : Prop := U.toFilter.sets S

/-- An ultrafilter contains no empty set; in particular not both `S` and `Sᶜ`. -/
theorem not_mem_and_compl (U : Ultrafilter I) (S : Sub I) :
    ¬ (U.toFilter.sets S ∧ U.toFilter.sets Sᶜ) := by
  rintro ⟨hS, hSc⟩
  -- S ∩ Sᶜ = ∅ ∈ U, contradicting properness.
  have : U.toFilter.sets (S ∩ᵤ Sᶜ) := U.toFilter.inter_mem hS hSc
  have he : (S ∩ᵤ Sᶜ) = empty := Sub.ext fun a => ⟨fun h => h.2 h.1, fun h => h.elim⟩
  exact U.toFilter.empty_not_mem (he ▸ this)

/-- Decisiveness as an exclusive disjunction: exactly one of `S`, `Sᶜ` belongs. -/
theorem mem_iff_compl_not_mem (U : Ultrafilter I) (S : Sub I) :
    U.toFilter.sets S ↔ ¬ U.toFilter.sets Sᶜ := by
  constructor
  · intro hS hSc; exact not_mem_and_compl U S ⟨hS, hSc⟩
  · intro hSc; rcases U.decide S with h | h
    · exact h
    · exact absurd h hSc

/-- Finite intersection: closure under binary `∩` (and hence all finite meets). -/
theorem inter_mem' (U : Ultrafilter I) {S T : Sub I} (hS : U.toFilter.sets S)
    (hT : U.toFilter.sets T) : U.toFilter.sets (S ∩ᵤ T) := U.toFilter.inter_mem hS hT

/-- Upward closure. -/
theorem up_closed' (U : Ultrafilter I) {S T : Sub I} (hS : U.toFilter.sets S) (hST : S ⊆ₛ T) :
    U.toFilter.sets T := U.toFilter.up_closed hS hST

/-- Members are inhabited. -/
theorem mem_nonempty (U : Ultrafilter I) {S : Sub I} (hS : U.toFilter.sets S) : ∃ a, S a :=
  Filter.mem_nonempty hS

/-- If a member splits as `S = S₁ ∪ S₂` (i.e. `Sᶜ = S₁ᶜ ∩ S₂ᶜ`) then the ultrafilter picks a side:
    whenever `Sᶜ ∉ U` and `S₁ᶜ ∩ S₂ᶜ ⊆ Sᶜ`, one of `S₁`, `S₂` is in `U`.  This is the prime-ideal
    behaviour the §1.646 representation uses to route each index decision to one branch. -/
theorem mem_of_union {U : Ultrafilter I} {S₁ S₂ : Sub I}
    (hU : U.toFilter.sets (fun a => S₁ a ∨ S₂ a)) : U.toFilter.sets S₁ ∨ U.toFilter.sets S₂ := by
  -- if neither S₁ nor S₂ is in U, both complements are, so (S₁∪S₂)ᶜ = S₁ᶜ ∩ S₂ᶜ ∈ U — contradiction.
  refine Classical.byContradiction (fun hcon => ?_)
  have h1 : ¬ U.toFilter.sets S₁ := fun h => hcon (Or.inl h)
  have h2 : ¬ U.toFilter.sets S₂ := fun h => hcon (Or.inr h)
  have hc1 : U.toFilter.sets S₁ᶜ := (U.decide S₁).resolve_left h1
  have hc2 : U.toFilter.sets S₂ᶜ := (U.decide S₂).resolve_left h2
  have hcap : U.toFilter.sets (S₁ᶜ ∩ᵤ S₂ᶜ) := U.toFilter.inter_mem hc1 hc2
  -- S₁ᶜ ∩ S₂ᶜ = (S₁ ∪ S₂)ᶜ
  have he : (S₁ᶜ ∩ᵤ S₂ᶜ) = (fun a => S₁ a ∨ S₂ a)ᶜ :=
    Sub.ext fun a => ⟨fun ⟨hn1, hn2⟩ ho => ho.elim hn1 hn2,
      fun hno => ⟨fun hh => hno (Or.inl hh), fun hh => hno (Or.inr hh)⟩⟩
  rw [he] at hcap
  exact not_mem_and_compl U (fun a => S₁ a ∨ S₂ a) ⟨hU, hcap⟩

end Ultrafilter

/-- **§1.646 entry point.**  Every filter base (a nonempty downward-directed family of nonempty sets —
    e.g. the principal coideals) is contained in an ultrafilter: each generator of the base is a member
    of the resulting ultrafilter.  This is exactly "an ultrafilter `F ⊇ principal coideals". -/
theorem exists_ultrafilter_of_base {I J : Type u} (B : Filter.Base I J) :
    ∃ U : Ultrafilter I, ∀ j, U.toFilter.sets (B.set j) := by
  obtain ⟨U, hU⟩ := exists_ultrafilter_le (Filter.ofBase B)
  exact ⟨U, fun j => hU (Filter.set_mem_ofBase B j)⟩

end Freyd.UF
