/-
  Freyd & Scedrov, *Categories and Allegories* §2.158
  The GRAPH MODEL of the free one-object representable allegory, and the
  decision procedure for containments in `Rel(S)`.

  Fix a set of labels `L`.  `LGraph L` is the category **G** of finite directed
  edge-LABELLED graphs with two distinguished vertices marked `s` and `t`
  (multiple edges, self-loops, and `s = t` all allowed).  Maps preserve
  incidence, direction, labels and the two marks.

  The book builds:
    • composition of two objects   = glue `t` of the first to `s` of the second;
    • coproduct of two objects     = glue the two `s`'s and the two `t`'s;
    • reciprocal of an object       = transpose the marks `s` and `t`
                                     (edges keep their direction);
    • `Ĝ` (`GHat`) the poset of `G°`: `G₁ ≤ G₂` iff there EXISTS a map `G₂ → G₁`;
      coproduct becomes intersection, composition a binary operation,
      reciprocation a unary operation — a ONE-OBJECT ALLEGORY;
    • `[A]` the graph `s ·--A-→· t`, and `Ḡ` the suballegory generated by them;
    • a representation `T : Ĝ → Rel(S)` for any labelled graph `T_s` on `S`:
      `x (T G) y` iff there is a graph map `f : G → T_s` with `f s = x`, `f t = y`.

  HEADLINE (Target 1, this file, Sorry-free): the DECISION PROCEDURE.
  A containment `E₁ ⊆ E₂` of allegorical terms holds in `Rel(S)` for every `S`
  iff there exists a graph map `[E₂] → [E₁]`.  The engine is a Yoneda-style
  lemma for pointed graph homomorphisms (`graph_yoneda`), proved via the
  tautological model (`T_s :=` the graph itself).

  Target 2: `Ĝ` is a genuine one-object `Allegory` (repo's class, §2.11).

  STRICTLY MATHLIB-FREE.  Only Lean 4 core + `Freyd.*`.
-/

import Freyd.S2_01

namespace Freyd.S2_158

/-! ## §2.158  The category **G** of labelled graphs

  A `Prop`-valued edge relation already lives at the level of the poset `Ĝ`:
  the axiom `A = A ∩ A` (§2.158) identifies two edges with the same label and
  endpoints, so edge *multiplicity* is irrelevant to `Ĝ`, to `T`, and to the
  decision procedure.  We therefore record, for each ordered pair of vertices
  and each label, merely WHETHER an edge is present. -/

/-- A directed edge-labelled graph with two distinguished vertices `s`, `t`.
    `edge u v A` says there is an `A`-labelled edge from `u` to `v`. -/
structure LGraph (L : Type) where
  V : Type
  edge : V → V → L → Prop
  s : V
  t : V

variable {L : Type}

/-- An EDGE homomorphism ignores the marks: it maps vertices to vertices and
    preserves every labelled directed edge.  This is the notion used for the
    representation `T` (where the target's marks are not looked at). -/
structure EHom (G H : LGraph L) where
  onV : G.V → H.V
  map_edge : ∀ {u v : G.V} {A : L}, G.edge u v A → H.edge (onV u) (onV v) A

/-- Identity edge-homomorphism. -/
def EHom.id (G : LGraph L) : EHom G G := ⟨fun x => x, fun h => h⟩

/-- Composition of edge-homomorphisms (diagram order: first `f`, then `g`). -/
def EHom.comp {G H K : LGraph L} (f : EHom G H) (g : EHom H K) : EHom G K :=
  ⟨fun x => g.onV (f.onV x), fun h => g.map_edge (f.map_edge h)⟩

/-- **The representation relation.**  Reading `H` as the labelled graph `T_s`
    (its marks ignored), `Trel G H x y` is `x (T G) y`: there is a graph map
    `G → H` carrying the mark `s` to `x` and the mark `t` to `y`. -/
def Trel (G H : LGraph L) (x y : H.V) : Prop :=
  ∃ f : EHom G H, f.onV G.s = x ∧ f.onV G.t = y

/-- A map in **G**: an edge-homomorphism that also preserves the two marks. -/
structure Hom (G H : LGraph L) where
  toEHom : EHom G H
  map_s : toEHom.onV G.s = H.s
  map_t : toEHom.onV G.t = H.t

/-- A `Hom G H` is exactly a `Trel G H` witnessed at the marks `(H.s, H.t)`. -/
theorem nonempty_hom_iff_trel_marks (G H : LGraph L) :
    Nonempty (Hom G H) ↔ Trel G H H.s H.t := by
  constructor
  · rintro ⟨h⟩; exact ⟨h.toEHom, h.map_s, h.map_t⟩
  · rintro ⟨f, hs, ht⟩; exact ⟨⟨f, hs, ht⟩⟩

/-! ## The Yoneda lemma for pointed graph homomorphisms

  `Ĝ`'s order is `G₁ ≤ G₂ ⇔ ∃ map G₂ → G₁`.  The tautological model
  (take `T_s := G₁` with the identity pointing) turns this order into the
  statement that the represented relation `T G₁` is contained in `T G₂` in
  every model.  This IS the decision procedure's core. -/

/-- **§2.158 core.**  `∃ map G₂ → G₁` (i.e. `G₁ ≤ G₂` in `Ĝ`) holds iff the
    represented relation of `G₁` is contained in that of `G₂` in EVERY model.
    Forward: precompose a map into any model with `G₂ → G₁`.  Backward: apply
    the hypothesis to the tautological model `H := G₁` pointed by the identity,
    which forces a map `G₂ → G₁`. -/
theorem graph_yoneda (G₁ G₂ : LGraph L) :
    Nonempty (Hom G₂ G₁) ↔
      ∀ (H : LGraph L) (x y : H.V), Trel G₁ H x y → Trel G₂ H x y := by
  constructor
  · rintro ⟨h⟩ H x y ⟨f, hfs, hft⟩
    refine ⟨EHom.comp h.toEHom f, ?_, ?_⟩
    · show f.onV (h.toEHom.onV G₂.s) = x; rw [h.map_s, hfs]
    · show f.onV (h.toEHom.onV G₂.t) = y; rw [h.map_t, hft]
  · intro hmono
    obtain ⟨f, hfs, hft⟩ := hmono G₁ G₁.s G₁.t ⟨EHom.id G₁, rfl, rfl⟩
    exact ⟨⟨f, hfs, hft⟩⟩

/-! ## §2.158  The allegory operations on graphs

  We realise each operation of the book directly on `LGraph L`, then prove that
  the representation `T = Trel · H` sends it to the matching operation on
  relations.  Gluing (`meet`, `comp`) uses `Quot` of the disjoint union of
  vertices along the identifications the book prescribes. -/

/-- The disjoint-union edge relation: an `inl-inl` edge is a `G₁`-edge, an
    `inr-inr` edge a `G₂`-edge, and there are no edges across the two copies. -/
def rawEdge (G₁ G₂ : LGraph L) : (G₁.V ⊕ G₂.V) → (G₁.V ⊕ G₂.V) → L → Prop :=
  fun p q A => match p, q with
    | Sum.inl a, Sum.inl b => G₁.edge a b A
    | Sum.inr a, Sum.inr b => G₂.edge a b A
    | _, _ => False

/-- Glue `G₁ ⊔ G₂` along `glueRel`, with marks named by `sv`, `tv`.  The edge
    relation is stated over representatives, so it respects the quotient with no
    congruence obligation. -/
def glued (G₁ G₂ : LGraph L) (glueRel : (G₁.V ⊕ G₂.V) → (G₁.V ⊕ G₂.V) → Prop)
    (sv tv : G₁.V ⊕ G₂.V) : LGraph L where
  V := Quot glueRel
  edge c d A := ∃ p q, Quot.mk glueRel p = c ∧ Quot.mk glueRel q = d ∧ rawEdge G₁ G₂ p q A
  s := Quot.mk glueRel sv
  t := Quot.mk glueRel tv

/-- A map OUT of a glued graph is a pair of component maps that agree along the
    identifications.  This is the `←` half of every gluing's universal property. -/
def gluedOut {G₁ G₂ : LGraph L} {glueRel : (G₁.V ⊕ G₂.V) → (G₁.V ⊕ G₂.V) → Prop}
    {sv tv : G₁.V ⊕ G₂.V} {H : LGraph L}
    (g₁ : EHom G₁ H) (g₂ : EHom G₂ H)
    (hagree : ∀ p p', glueRel p p' →
      Sum.elim g₁.onV g₂.onV p = Sum.elim g₁.onV g₂.onV p') :
    EHom (glued G₁ G₂ glueRel sv tv) H where
  onV := Quot.lift (Sum.elim g₁.onV g₂.onV) hagree
  map_edge := by
    intro c d A
    rintro ⟨p, q, rfl, rfl, hraw⟩
    show H.edge (Sum.elim g₁.onV g₂.onV p) (Sum.elim g₁.onV g₂.onV q) A
    cases p with
    | inl a => cases q with
      | inl b => exact g₁.map_edge hraw
      | inr b => exact hraw.elim
    | inr a => cases q with
      | inl b => exact hraw.elim
      | inr b => exact g₂.map_edge hraw

/-- The identity object `1`: one vertex, no edges, `s = t`.  Represents the
    identity relation. -/
def one : LGraph L := ⟨Unit, fun _ _ _ => False, (), ()⟩

/-- Reciprocal: transpose the marks `s` and `t`, keeping edge directions. -/
def recip (G : LGraph L) : LGraph L := ⟨G.V, G.edge, G.t, G.s⟩

/-- Intersection object (`coproduct` in **G**): glue the two `s`'s and the two
    `t`'s. -/
def meetRel (G₁ G₂ : LGraph L) : (G₁.V ⊕ G₂.V) → (G₁.V ⊕ G₂.V) → Prop :=
  fun p q => match p, q with
    | Sum.inl a, Sum.inr b => (a = G₁.s ∧ b = G₂.s) ∨ (a = G₁.t ∧ b = G₂.t)
    | _, _ => False

def meet (G₁ G₂ : LGraph L) : LGraph L :=
  glued G₁ G₂ (meetRel G₁ G₂) (Sum.inl G₁.s) (Sum.inl G₁.t)

/-- Composition object (diagram order): glue `t` of `G₁` to `s` of `G₂`. -/
def compRel (G₁ G₂ : LGraph L) : (G₁.V ⊕ G₂.V) → (G₁.V ⊕ G₂.V) → Prop :=
  fun p q => match p, q with
    | Sum.inl a, Sum.inr b => a = G₁.t ∧ b = G₂.s
    | _, _ => False

def gcomp (G₁ G₂ : LGraph L) : LGraph L :=
  glued G₁ G₂ (compRel G₁ G₂) (Sum.inl G₁.s) (Sum.inr G₂.t)

/-! ### `T` preserves the operations -/

/-- `T 1 = 1`: the identity object represents equality. -/
theorem Trel_one (H : LGraph L) (x y : H.V) : Trel one H x y ↔ x = y := by
  constructor
  · rintro ⟨f, hs, ht⟩; exact hs.symm.trans ht
  · rintro rfl; exact ⟨⟨fun _ => x, fun h => h.elim⟩, rfl, rfl⟩

/-- `T (G°) = (T G)°`: reciprocation of graphs becomes reciprocation of relations. -/
theorem Trel_recip (G H : LGraph L) (x y : H.V) :
    Trel (recip G) H x y ↔ Trel G H y x := by
  constructor
  · rintro ⟨f, hs, ht⟩; exact ⟨⟨f.onV, f.map_edge⟩, ht, hs⟩
  · rintro ⟨f, hs, ht⟩; exact ⟨⟨f.onV, f.map_edge⟩, ht, hs⟩

/-- `T (G₁ ∩ G₂) = T G₁ ∩ T G₂`. -/
theorem Trel_meet (G₁ G₂ H : LGraph L) (x y : H.V) :
    Trel (meet G₁ G₂) H x y ↔ Trel G₁ H x y ∧ Trel G₂ H x y := by
  constructor
  · rintro ⟨f, hfs, hft⟩
    refine ⟨⟨⟨fun a => f.onV (Quot.mk _ (Sum.inl a)), ?_⟩, hfs, hft⟩,
            ⟨⟨fun b => f.onV (Quot.mk _ (Sum.inr b)), ?_⟩, ?_, ?_⟩⟩
    · intro a b A hab; exact f.map_edge ⟨Sum.inl a, Sum.inl b, rfl, rfl, hab⟩
    · intro a b A hab; exact f.map_edge ⟨Sum.inr a, Sum.inr b, rfl, rfl, hab⟩
    · show f.onV (Quot.mk (meetRel G₁ G₂) (Sum.inr G₂.s)) = x
      rw [← Quot.sound (r := meetRel G₁ G₂) (a := Sum.inl G₁.s) (b := Sum.inr G₂.s)
        (Or.inl ⟨rfl, rfl⟩)]
      exact hfs
    · show f.onV (Quot.mk (meetRel G₁ G₂) (Sum.inr G₂.t)) = y
      rw [← Quot.sound (r := meetRel G₁ G₂) (a := Sum.inl G₁.t) (b := Sum.inr G₂.t)
        (Or.inr ⟨rfl, rfl⟩)]
      exact hft
  · rintro ⟨⟨g₁, hg1s, hg1t⟩, ⟨g₂, hg2s, hg2t⟩⟩
    refine ⟨gluedOut g₁ g₂ ?_, ?_, ?_⟩
    · rintro p p' hpp'
      cases p with
      | inl a => cases p' with
        | inl b => exact hpp'.elim
        | inr b => rcases hpp' with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
                   · exact hg1s.trans hg2s.symm
                   · exact hg1t.trans hg2t.symm
      | inr a => exact hpp'.elim
    · show Sum.elim g₁.onV g₂.onV (Sum.inl G₁.s) = x; exact hg1s
    · show Sum.elim g₁.onV g₂.onV (Sum.inl G₁.t) = y; exact hg1t

/-- `T (G₁ ; G₂) = T G₁ ∘ T G₂` (relational composition, diagram order). -/
theorem Trel_gcomp (G₁ G₂ H : LGraph L) (x y : H.V) :
    Trel (gcomp G₁ G₂) H x y ↔ ∃ z, Trel G₁ H x z ∧ Trel G₂ H z y := by
  constructor
  · rintro ⟨f, hfs, hft⟩
    refine ⟨f.onV (Quot.mk _ (Sum.inl G₁.t)),
            ⟨⟨fun a => f.onV (Quot.mk _ (Sum.inl a)), ?_⟩, hfs, rfl⟩,
            ⟨⟨fun b => f.onV (Quot.mk _ (Sum.inr b)), ?_⟩, ?_, hft⟩⟩
    · intro a b A hab; exact f.map_edge ⟨Sum.inl a, Sum.inl b, rfl, rfl, hab⟩
    · intro a b A hab; exact f.map_edge ⟨Sum.inr a, Sum.inr b, rfl, rfl, hab⟩
    · show f.onV (Quot.mk (compRel G₁ G₂) (Sum.inr G₂.s))
            = f.onV (Quot.mk (compRel G₁ G₂) (Sum.inl G₁.t))
      rw [Quot.sound (r := compRel G₁ G₂) (a := Sum.inl G₁.t) (b := Sum.inr G₂.s) ⟨rfl, rfl⟩]
  · rintro ⟨z, ⟨g₁, hg1s, hg1t⟩, ⟨g₂, hg2s, hg2t⟩⟩
    refine ⟨gluedOut g₁ g₂ ?_, ?_, ?_⟩
    · rintro p p' hpp'
      cases p with
      | inl a => cases p' with
        | inl b => exact hpp'.elim
        | inr b => rcases hpp' with ⟨rfl, rfl⟩; exact hg1t.trans hg2s.symm
      | inr a => exact hpp'.elim
    · show Sum.elim g₁.onV g₂.onV (Sum.inl G₁.s) = x; exact hg1s
    · show Sum.elim g₁.onV g₂.onV (Sum.inr G₂.t) = y; exact hg2t

/-! ## §2.158  Terms, `[·]`, and the DECISION PROCEDURE

  `[A]` is the arrow graph `s ·--A-→· t`.  An allegorical term is interpreted
  two ways: as a graph `[E]` (`toGraph`, built from the `[A]`'s and the graph
  operations) and, in a model `H = T_s`, as a relation `⟦E⟧` (`toRel`).  The
  bridge `toRel_eq_Trel` says `x ⟦E⟧ y ↔ x (T [E]) y`, i.e. the relation is the
  represented relation of the graph.  Feeding this into `graph_yoneda` yields:
  a containment `E₁ ⊆ E₂` holds in every `Rel(S)` iff there is a graph map
  `[E₂] → [E₁]`. -/

/-- The arrow graph `[A]`: two vertices `false = s`, `true = t`, one
    `A`-labelled edge `s → t`. -/
def arrow (A : L) : LGraph L where
  V := Bool
  edge p q B := p = false ∧ q = true ∧ B = A
  s := false
  t := true

/-- The defining edge `s → t` of the arrow graph. -/
theorem arrow_edge (A : L) : (arrow A).edge (arrow A).s (arrow A).t A :=
  ⟨rfl, rfl, rfl⟩

/-- `T [A] = A`: the represented relation of the arrow graph is the label's
    relation in the model. -/
theorem Trel_arrow (A : L) (H : LGraph L) (x y : H.V) :
    Trel (arrow A) H x y ↔ H.edge x y A := by
  constructor
  · rintro ⟨f, hs, ht⟩
    have he := f.map_edge (arrow_edge A)
    rw [hs, ht] at he; exact he
  · intro h
    refine ⟨⟨fun p => cond p y x, ?_⟩, rfl, rfl⟩
    rintro p q B ⟨rfl, rfl, rfl⟩; exact h

/-- Allegorical terms over the labels `L`. -/
inductive Term (L : Type) where
  | var : L → Term L
  | one : Term L
  | recip : Term L → Term L
  | meet : Term L → Term L → Term L
  | comp : Term L → Term L → Term L

/-- `[E]`: the graph of a term, built from the arrow graphs and the graph
    operations. -/
def toGraph : Term L → LGraph L
  | .var A => arrow A
  | .one => one
  | .recip e => recip (toGraph e)
  | .meet a b => meet (toGraph a) (toGraph b)
  | .comp a b => gcomp (toGraph a) (toGraph b)

/-- `⟦E⟧`: the relation of a term in the model `H` (labels ↦ `H`-edges). -/
def toRel (H : LGraph L) : Term L → H.V → H.V → Prop
  | .var A, x, y => H.edge x y A
  | .one, x, y => x = y
  | .recip e, x, y => toRel H e y x
  | .meet a b, x, y => toRel H a x y ∧ toRel H b x y
  | .comp a b, x, y => ∃ z, toRel H a x z ∧ toRel H b z y

/-- **The representation is the graph model.**  `x ⟦E⟧ y ↔ x (T [E]) y`: the
    relation a term denotes in `H` is exactly the represented relation of its
    graph.  Proof: induction on the term, discharging each step by the matching
    `T`-preservation lemma. -/
theorem toRel_eq_Trel (H : LGraph L) (e : Term L) (x y : H.V) :
    toRel H e x y ↔ Trel (toGraph e) H x y := by
  induction e generalizing x y with
  | var A => exact (Trel_arrow A H x y).symm
  | one => exact (Trel_one H x y).symm
  | recip e ih =>
      show toRel H e y x ↔ Trel (recip (toGraph e)) H x y
      rw [Trel_recip]; exact ih y x
  | meet a b iha ihb =>
      show toRel H a x y ∧ toRel H b x y ↔ Trel (meet (toGraph a) (toGraph b)) H x y
      rw [Trel_meet, iha, ihb]
  | comp a b iha ihb =>
      show (∃ z, toRel H a x z ∧ toRel H b z y)
            ↔ Trel (gcomp (toGraph a) (toGraph b)) H x y
      rw [Trel_gcomp]
      constructor
      · rintro ⟨z, h1, h2⟩; exact ⟨z, (iha x z).mp h1, (ihb z y).mp h2⟩
      · rintro ⟨z, h1, h2⟩; exact ⟨z, (iha x z).mpr h1, (ihb z y).mpr h2⟩

/-- **§2.158 DECISION PROCEDURE (Target 1).**  A containment `E₁ ⊆ E₂` of
    allegorical terms holds in `Rel(S)` for EVERY model `S` (here: every
    labelled graph `H`, its vertices as the set and its edges as the labels'
    relations) iff there exists a graph map `[E₂] → [E₁]`.  Since graph maps
    between the two finite graphs are decidable, this is Freyd's decision
    procedure for the equational theory of `Rel(S)`. -/
theorem decision (E₁ E₂ : Term L) :
    (∀ (H : LGraph L) (x y : H.V), toRel H E₁ x y → toRel H E₂ x y)
      ↔ Nonempty (Hom (toGraph E₂) (toGraph E₁)) := by
  rw [graph_yoneda]
  constructor
  · intro h H x y hE1
    exact (toRel_eq_Trel H E₂ x y).mp (h H x y ((toRel_eq_Trel H E₁ x y).mpr hE1))
  · intro h H x y hE1
    exact (toRel_eq_Trel H E₂ x y).mpr (h H x y ((toRel_eq_Trel H E₁ x y).mp hE1))

/-! ## §2.158  `Ĝ` is a one-object allegory (Target 2)

  `Ĝ = GHat` is `LGraph L` modulo `grel` (equal represented relation in every
  model — the same, by `graph_yoneda`, as the book's "identify `G₁`, `G₂` when
  `G₁ ≤ G₂ ≤ G₁`").  Each allegory axiom is a `grel`-identity that, after the
  `T`-preservation lemmas, becomes a first-order tautology about `∃`/`∧`/`=`
  on the represented relations — Freyd's "T preserves the allegory operations",
  used here to transport the laws of `Rel(S)` onto `Ĝ`. -/

/-- `grel G₁ G₂`: `G₁` and `G₂` represent the same relation in every model.  By
    `graph_yoneda` this is exactly mutual `≤` in `Ĝ`. -/
def grel (G₁ G₂ : LGraph L) : Prop :=
  ∀ (H : LGraph L) (x y : H.V), Trel G₁ H x y ↔ Trel G₂ H x y

theorem grel_refl (G : LGraph L) : grel G G := fun _ _ _ => Iff.rfl
theorem grel_symm {G₁ G₂ : LGraph L} (h : grel G₁ G₂) : grel G₂ G₁ :=
  fun H x y => (h H x y).symm
theorem grel_trans {G₁ G₂ G₃ : LGraph L} (h₁ : grel G₁ G₂) (h₂ : grel G₂ G₃) :
    grel G₁ G₃ := fun H x y => (h₁ H x y).trans (h₂ H x y)

/-! ### Congruence of the operations for `grel` -/

theorem recip_congr {G₁ G₂ : LGraph L} (h : grel G₁ G₂) :
    grel (recip G₁) (recip G₂) := by
  intro H x y; simp only [Trel_recip]; exact h H y x

theorem meet_congr {G₁ G₁' G₂ G₂' : LGraph L} (h₁ : grel G₁ G₁') (h₂ : grel G₂ G₂') :
    grel (meet G₁ G₂) (meet G₁' G₂') := by
  intro H x y; simp only [Trel_meet]
  constructor
  · rintro ⟨ha, hb⟩; exact ⟨(h₁ H x y).mp ha, (h₂ H x y).mp hb⟩
  · rintro ⟨ha, hb⟩; exact ⟨(h₁ H x y).mpr ha, (h₂ H x y).mpr hb⟩

theorem gcomp_congr {G₁ G₁' G₂ G₂' : LGraph L} (h₁ : grel G₁ G₁') (h₂ : grel G₂ G₂') :
    grel (gcomp G₁ G₂) (gcomp G₁' G₂') := by
  intro H x y; simp only [Trel_gcomp]
  constructor
  · rintro ⟨z, ha, hb⟩; exact ⟨z, (h₁ H x z).mp ha, (h₂ H z y).mp hb⟩
  · rintro ⟨z, ha, hb⟩; exact ⟨z, (h₁ H x z).mpr ha, (h₂ H z y).mpr hb⟩

/-! ### The allegory laws as `grel`-identities -/

theorem recip_recip_law (G : LGraph L) : grel (recip (recip G)) G := by
  intro H x y; simp only [Trel_recip]

theorem recip_gcomp_law (G₁ G₂ : LGraph L) :
    grel (recip (gcomp G₁ G₂)) (gcomp (recip G₂) (recip G₁)) := by
  intro H x y; simp only [Trel_recip, Trel_gcomp]
  constructor <;> rintro ⟨z, h1, h2⟩ <;> exact ⟨z, h2, h1⟩

theorem recip_meet_law (G₁ G₂ : LGraph L) :
    grel (recip (meet G₁ G₂)) (meet (recip G₁) (recip G₂)) := by
  intro H x y; simp only [Trel_recip, Trel_meet]

theorem meet_idem_law (G : LGraph L) : grel (meet G G) G := by
  intro H x y; simp only [Trel_meet, and_self]

theorem meet_comm_law (G₁ G₂ : LGraph L) : grel (meet G₁ G₂) (meet G₂ G₁) := by
  intro H x y; simp only [Trel_meet]; exact and_comm

theorem meet_assoc_law (G₁ G₂ G₃ : LGraph L) :
    grel (meet G₁ (meet G₂ G₃)) (meet (meet G₁ G₂) G₃) := by
  intro H x y; simp only [Trel_meet]; exact and_assoc.symm

theorem one_gcomp_law (G : LGraph L) : grel (gcomp one G) G := by
  intro H x y; simp only [Trel_gcomp, Trel_one]
  constructor
  · rintro ⟨z, rfl, h⟩; exact h
  · intro h; exact ⟨x, rfl, h⟩

theorem gcomp_one_law (G : LGraph L) : grel (gcomp G one) G := by
  intro H x y; simp only [Trel_gcomp, Trel_one]
  constructor
  · rintro ⟨z, h, rfl⟩; exact h
  · intro h; exact ⟨y, h, rfl⟩

theorem gcomp_assoc_law (G₁ G₂ G₃ : LGraph L) :
    grel (gcomp (gcomp G₁ G₂) G₃) (gcomp G₁ (gcomp G₂ G₃)) := by
  intro H x y; simp only [Trel_gcomp]
  constructor
  · rintro ⟨z, ⟨w, h1, h2⟩, h3⟩; exact ⟨w, h1, z, h2, h3⟩
  · rintro ⟨w, h1, z, h2, h3⟩; exact ⟨z, ⟨w, h1, h2⟩, h3⟩

theorem semidistrib_law (R S T : LGraph L) :
    grel (gcomp R (meet S T))
      (meet (meet (gcomp R S) (gcomp R (meet S T))) (gcomp R T)) := by
  intro H x y; simp only [Trel_meet, Trel_gcomp]
  constructor
  · rintro ⟨z, hr, hs, ht⟩
    exact ⟨⟨⟨z, hr, hs⟩, ⟨z, hr, hs, ht⟩⟩, ⟨z, hr, ht⟩⟩
  · intro hR; exact hR.1.2

theorem modular_law (R S T : LGraph L) :
    grel (meet (gcomp R S) T)
      (meet (meet (gcomp R S) T) (gcomp (meet R (gcomp T (recip S))) S)) := by
  intro H x y; simp only [Trel_meet, Trel_gcomp, Trel_recip]
  constructor
  · rintro ⟨⟨u, hru, hsu⟩, hty⟩
    exact ⟨⟨⟨u, hru, hsu⟩, hty⟩, ⟨u, ⟨hru, y, hty, hsu⟩, hsu⟩⟩
  · intro hR; exact hR.1

/-! ### The quotient `Ĝ = GHat` and the one-object allegory -/

open Freyd
open Freyd.Alg (Allegory)

/-- The setoid on graphs: identify `G₁, G₂` when they represent equal relations
    (equivalently, mutual `≤` — Freyd's `Ĝ = poset of G°`). -/
instance graphSetoid : Setoid (LGraph L) := ⟨grel, ⟨grel_refl, grel_symm, grel_trans⟩⟩

/-- `Ĝ`: graphs modulo `grel`.  Carries the one-object allegory of §2.158.
    `abbrev` (reducible) so the `Quotient` recursors see through it.  Lives in
    `Type 1` since `LGraph L` carries a `Type`-valued vertex field. -/
abbrev GHat (L : Type) := Quotient (graphSetoid : Setoid (LGraph L))

/-- The class of a graph in `Ĝ`. -/
def ghat (G : LGraph L) : GHat L := Quotient.mk graphSetoid G

/-- Reciprocation descends to `Ĝ`. -/
def ghatRecip : GHat L → GHat L :=
  Quotient.lift (fun G => ghat (recip G)) (fun _ _ h => Quotient.sound (recip_congr h))

/-- Intersection descends to `Ĝ`. -/
def ghatMeet : GHat L → GHat L → GHat L :=
  Quotient.lift₂ (fun G₁ G₂ => ghat (meet G₁ G₂))
    (fun _ _ _ _ h₁ h₂ => Quotient.sound (meet_congr h₁ h₂))

/-- Composition descends to `Ĝ`. -/
def ghatComp : GHat L → GHat L → GHat L :=
  Quotient.lift₂ (fun G₁ G₂ => ghat (gcomp G₁ G₂))
    (fun _ _ _ _ h₁ h₂ => Quotient.sound (gcomp_congr h₁ h₂))

/-- The single object `*` of the one-object allegory `Ĝ`. -/
inductive GStar (L : Type) where
  | star

/-- **§2.158**: `Ĝ` is a category — the single object `*` with hom-set `GHat L`,
    composition the descended graph-composition, identity the one-vertex graph. -/
instance ghatCat : Cat (GStar L) where
  Hom _ _ := GHat L
  id _ := ghat one
  comp R S := ghatComp R S
  id_comp f := by
    refine Quotient.inductionOn f (fun G => ?_); exact Quotient.sound (one_gcomp_law G)
  comp_id f := by
    refine Quotient.inductionOn f (fun G => ?_); exact Quotient.sound (gcomp_one_law G)
  assoc f g h := by
    refine Quotient.inductionOn₃ f g h (fun G₁ G₂ G₃ => ?_)
    exact Quotient.sound (gcomp_assoc_law G₁ G₂ G₃)

/-! The allegory obligations, stated directly on `GHat L` so the `Quotient`
    recursors unfold cleanly.  (Inside the `Allegory` instance the hom-set is the
    inherited `Cat.Hom`, whose unfolding to `GHat L` is unreliable.) -/

theorem ghat_recip_recip (R : GHat L) : ghatRecip (ghatRecip R) = R := by
  refine Quotient.inductionOn R (fun G => ?_); exact Quotient.sound (recip_recip_law G)

theorem ghat_recip_comp (R S : GHat L) :
    ghatRecip (ghatComp R S) = ghatComp (ghatRecip S) (ghatRecip R) := by
  refine Quotient.inductionOn₂ R S (fun G₁ G₂ => ?_)
  exact Quotient.sound (recip_gcomp_law G₁ G₂)

theorem ghat_recip_inter (R S : GHat L) :
    ghatRecip (ghatMeet R S) = ghatMeet (ghatRecip R) (ghatRecip S) := by
  refine Quotient.inductionOn₂ R S (fun G₁ G₂ => ?_)
  exact Quotient.sound (recip_meet_law G₁ G₂)

theorem ghat_inter_idem (R : GHat L) : ghatMeet R R = R := by
  refine Quotient.inductionOn R (fun G => ?_); exact Quotient.sound (meet_idem_law G)

theorem ghat_inter_comm (R S : GHat L) : ghatMeet R S = ghatMeet S R := by
  refine Quotient.inductionOn₂ R S (fun G₁ G₂ => ?_)
  exact Quotient.sound (meet_comm_law G₁ G₂)

/-- Associativity of `∩` on `Ĝ`. -/
theorem ghat_inter_assoc (R S T : GHat L) :
    ghatMeet R (ghatMeet S T) = ghatMeet (ghatMeet R S) T := by
  obtain ⟨G₁, rfl⟩ := Quotient.exists_rep R
  obtain ⟨G₂, rfl⟩ := Quotient.exists_rep S
  obtain ⟨G₃, rfl⟩ := Quotient.exists_rep T
  exact Quotient.sound (meet_assoc_law G₁ G₂ G₃)

/-- Semi-distributivity on `Ĝ`. -/
theorem ghat_semidistrib (R S T : GHat L) :
    ghatComp R (ghatMeet S T)
      = ghatMeet (ghatMeet (ghatComp R S) (ghatComp R (ghatMeet S T))) (ghatComp R T) := by
  obtain ⟨G₁, rfl⟩ := Quotient.exists_rep R
  obtain ⟨G₂, rfl⟩ := Quotient.exists_rep S
  obtain ⟨G₃, rfl⟩ := Quotient.exists_rep T
  exact Quotient.sound (semidistrib_law G₁ G₂ G₃)

/-- The modular law on `Ĝ`. -/
theorem ghat_modular (R S T : GHat L) :
    ghatMeet (ghatComp R S) T
      = ghatMeet (ghatMeet (ghatComp R S) T)
          (ghatComp (ghatMeet R (ghatComp T (ghatRecip S))) S) := by
  obtain ⟨G₁, rfl⟩ := Quotient.exists_rep R
  obtain ⟨G₂, rfl⟩ := Quotient.exists_rep S
  obtain ⟨G₃, rfl⟩ := Quotient.exists_rep T
  exact Quotient.sound (modular_law G₁ G₂ G₃)

/-- **§2.158 (Target 2)**: `Ĝ` is a genuine one-object `Allegory` (repo class,
    §2.11).  Every axiom is transported from `Rel(S)` through the `grel`-laws. -/
instance ghatAllegory : Allegory (GStar L) where
  toCat := ghatCat
  recip R := ghatRecip R
  inter R S := ghatMeet R S
  recip_recip R := ghat_recip_recip R
  recip_comp R S := ghat_recip_comp R S
  recip_inter R S := ghat_recip_inter R S
  inter_idem R := ghat_inter_idem R
  inter_comm R S := ghat_inter_comm R S
  inter_assoc R S T := ghat_inter_assoc R S T
  semidistrib R S T := ghat_semidistrib R S T
  modular R S T := ghat_modular R S T

/-! ## §2.158  The recast SEPARATED axioms (Target 3, partial)

  Toward "no finite set of equations accounts for `Rel(S)`", Freyd first recasts
  the allegory axioms so that — apart from `R ∩ S ⊆ R` and the specific
  `A ⊆ A ∩ A` — every containment is *separated* (each variable occurs exactly
  once on each side).  We prove the three recast forms are valid containments in
  the graph model, i.e. hold in `Rel(S)` for every `S` (this is the FORWARD
  direction of the recasting: the separated forms follow from the allegory
  axioms, since `Ĝ` is an allegory).  The full no-finite-axiomatizability
  metatheorem (the rhombus-chain family) is left open — see the module report. -/

/-- The represented-relation order: `G₁ ⊆ G₂` in every model.  By `graph_yoneda`
    this is exactly `∃ map G₂ → G₁`, i.e. `G₁ ≤ G₂` in `Ĝ`. -/
def Gle (G₁ G₂ : LGraph L) : Prop :=
  ∀ (H : LGraph L) (x y : H.V), Trel G₁ H x y → Trel G₂ H x y

/-- Recast specific axiom `A ⊆ A ∩ A` (the one non-separated containment left,
    besides `R ∩ S ⊆ R`): valid in every model. -/
theorem sep_inter_idem (A : L) : Gle (arrow A) (meet (arrow A) (arrow A)) := by
  intro H x y h; rw [Trel_meet]; exact ⟨h, h⟩

/-- Recast SEPARATED semi-distributivity:
    `(R₁ ∩ R₂)(S₁ ∩ S₂) ⊆ R₁S₁ ∩ R₂S₂`.  Valid in every model. -/
theorem sep_semidistrib (R₁ R₂ S₁ S₂ : LGraph L) :
    Gle (gcomp (meet R₁ R₂) (meet S₁ S₂)) (meet (gcomp R₁ S₁) (gcomp R₂ S₂)) := by
  intro H x y h
  simp only [Trel_gcomp, Trel_meet] at h ⊢
  obtain ⟨z, ⟨hr1, hr2⟩, hs1, hs2⟩ := h
  exact ⟨⟨z, hr1, hs1⟩, ⟨z, hr2, hs2⟩⟩

/-- Recast SEPARATED modular law:
    `R(S₁ ∩ S₂) ∩ T ⊆ (R ∩ TS₁°)S₂`.  Valid in every model. -/
theorem sep_modular (R S₁ S₂ T : LGraph L) :
    Gle (meet (gcomp R (meet S₁ S₂)) T)
      (gcomp (meet R (gcomp T (recip S₁))) S₂) := by
  intro H x y h
  simp only [Trel_gcomp, Trel_meet, Trel_recip] at h ⊢
  obtain ⟨⟨z, hr, hs1, hs2⟩, ht⟩ := h
  exact ⟨z, ⟨hr, y, ht, hs1⟩, hs2⟩

end Freyd.S2_158
