/-
  Freyd & Scedrov, *Categories and Allegories* §2.417 — Target 3, faithful-label analysis.
  "A generator (as opposed to a progenitor) is not good enough."

  §2.417 asserts, "just as in [1.96(10)], the only object of `C` with a power-object is the
  coterminator", whence `Rel(C)` is NOT a power allegory.  `S2_417b_NotPower.lean` flagged
  that over a FIXED label SET the negation `¬ RelCIsPowerAllegory` is not reachable and asked
  for a "faithful label universe".  This file settles precisely what is and is not reachable,
  with a sorry-free THEOREM (not a comment) capturing the actual §1.96(10) mechanism.

  ## Why the collapse is genuinely a PROPER-CLASS phenomenon (so `¬ RelCIsPowerAllegory` is
  ## NOT faithfully reachable in Lean, and is in fact FALSE for every label type `L : Type`).

  Read §1.96(10)/§2.417 exactly.  The would-be power-object of the terminator, `[1] = Ω`, is
  the SUBOBJECT CLASSIFIER, and its points are the "sieves"/right-ideals of the transition
  monoid generated by the label actions `x ↦ xᵃ`.  Two facts pin the mechanism down:

    * Freyd's own remark: the automorphic subcategory `B` (each action a bijection) has the
      SAME unbounded label universe yet IS a topos, with `Ω = 2`.  So the obstruction is NOT
      "labels are unbounded" per se — it is that with NON-invertible actions the free monoid on
      the labels has a PROPER CLASS of right-ideals, so `Ω` is a proper class and cannot exist.

    * For any label `L : Type` the transition monoid is a set (its right-ideals form the set
      `𝒫(FreeMonoid L)`), so `Ω` EXISTS as a set: `C` has all power-objects and
      `RelCIsPowerAllegory L` is TRUE.  Hence `¬ RelCIsPowerAllegory L` is FALSE, for every
      `L`, and asserting it (with any encoding whose labels form a Lean type) would be
      false-with-a-hole.  Lean has no proper classes; an object may activate ALL of `L` (its
      active set is an arbitrary `L → Prop`, exactly as Freyd's active set is an arbitrary SET),
      so no `L : Type` re-encoding can be faithful to the proper-class quantifier.

  ## The sharpest concrete collapse that IS true and Lean-provable — the growth mechanism.

  What survives, and is proved here sorry-free, is the finite/countable rung of the collapse:
  as soon as `L` carries ONE label `ℓ` (one non-invertible action), the power-object of the
  terminator — a NON-coterminator — is forced to have an INFINITE carrier.  In the proper-class
  limit (proper-class-many independent labels) this forced size is a proper class, which is the
  §1.96(10) non-existence.  Concretely:

    * `succObj ℓ`  — the free object on one label: carrier `ℕ`, `ℓ` acting as successor.
    * `upRel ℓ k`  — the closed subobjects `[k,∞) ⊆ ℕ`, an equivariant relation `succObj ℓ → 1`.
      These are pairwise distinct, giving `ℕ ↪ Rel(succObj ℓ, 1)`.
    * `terminator_power_carrier_infinite` (HEADLINE) — if `mem : P → 1` is a power-object of
      the terminator then `P.S` admits an injection from `ℕ`: the classifiers of the `[k,∞)`
      are pairwise distinct maps `succObj ℓ → P`, each pinned by its value at `0`.
    * `terminator_no_finite_power_object` / `terminator_oneObj_not_power` — concrete
      non-representability witnesses: no finite object (in particular not the terminator itself)
      is a power-object of the terminator.

  MATHLIB-FREE.  Axioms ⊆ {propext, Classical.choice, Quot.sound}.
-/

module

public import Freyd.S2_417b_NotPower

namespace Freyd.S2_417
open Freyd

-- Classical decidability so `exp` can branch on the Prop-valued membership `A a`.
attribute [local instance] Classical.propDecidable

variable {L : Type}

/-! ## §2.417  The free object on one label `ℓ`: carrier `ℕ`, `ℓ` acting as successor. -/

/-- `succObj ℓ`: carrier `ℕ`, default `s = id`, the single active label `ℓ` acting as
    successor (`nᵃ = n+1` for `a = ℓ`, `nᵃ = n` otherwise).  This is the free object on the
    one non-invertible generator `ℓ`; its closed subobjects are exactly the up-sets `[k,∞)`. -/
def succObj (ℓ : L) : Obj L where
  S := Nat
  s := fun n => n
  A := fun a => a = ℓ
  f := fun _ n => n + 1

/-- The action of the generator `ℓ` on `succObj ℓ` is successor. -/
theorem exp_succ (ℓ : L) (n : Nat) : exp (succObj ℓ) n ℓ = n + 1 := by
  show (if (succObj ℓ).A ℓ then (succObj ℓ).f ℓ n else (succObj ℓ).s n) = n + 1
  simp only [succObj, if_pos]

/-- Every action of `succObj ℓ` is monotone increasing (`n ≤ nᵃ`); needed for closure. -/
theorem le_exp_succ (ℓ : L) (a : L) (n : Nat) : n ≤ exp (succObj ℓ) n a := by
  show n ≤ (if (succObj ℓ).A a then (succObj ℓ).f a n else (succObj ℓ).s n)
  by_cases h : (succObj ℓ).A a
  · rw [if_pos h]; exact Nat.le_succ n
  · rw [if_neg h]; exact Nat.le_refl n

/-! ## §2.417  The closed subobjects `[k,∞)` of `succObj ℓ` as relations into the terminator. -/

/-- `upRel ℓ k : succObj ℓ → 1` — the up-set `[k,∞)` viewed as an equivariant relation into the
    terminator.  Equivariant because every action of `succObj ℓ` is increasing. -/
def upRel (ℓ : L) (k : Nat) : CRel (succObj ℓ) (oneObj L) where
  rel n _ := k ≤ n
  equiv a n _ h := Nat.le_trans h (le_exp_succ ℓ a n)

/-! ## §2.417  A map out of `succObj ℓ` is pinned by its value at `0`. -/

/-- Any two `C`-maps `succObj ℓ → P` that agree at `0` agree everywhere: the generator `ℓ`
    acts as successor, so equivariance propagates the value at `0` up the chain `0,1,2,…`. -/
theorem map_det (ℓ : L) {P : Obj L} (g g' : CHom (succObj ℓ) P)
    (h0 : g.g (0 : Nat) = g'.g (0 : Nat)) : ∀ n : Nat, g.g n = g'.g n := by
  intro n
  induction n with
  | zero => exact h0
  | succ m ih =>
      have e1 : g.g (m + 1) = exp P (g.g m) ℓ := by
        rw [← exp_succ ℓ m]; exact g.equiv ℓ m
      have e2 : g'.g (m + 1) = exp P (g'.g m) ℓ := by
        rw [← exp_succ ℓ m]; exact g'.equiv ℓ m
      rw [e1, e2, ih]

/-! ## §2.417 (target 3, faithful rung).  The power-object of the terminator is INFINITE. -/

/-- **HEADLINE.**  If `mem : P → 1` is a power-object of the terminator `1 = oneObj L` in
    `Rel(C)`, then `P`'s carrier admits an injection from `ℕ` — it is infinite.

    Proof: the closed subobjects `[k,∞) = upRel ℓ k` are pairwise distinct equivariant
    relations `succObj ℓ → 1`, so their classifiers `cls k : succObj ℓ → P` are pairwise
    distinct, and each is pinned by its value at `0` (`map_det`); the resulting
    `k ↦ (cls k).g 0 : ℕ → P.S` is injective.  This is the finite/countable rung of Freyd's
    §1.96(10) collapse: one non-invertible label already forces the classifier to be infinite;
    proper-class-many independent labels force it to be a proper class — the non-existence. -/
theorem terminator_power_carrier_infinite (ℓ : L) {P : Obj L}
    {mem : CRel P (oneObj L)} (h : IsPowerObj (oneObj L) P mem) :
    ∃ e : Nat → P.S, ∀ i j, e i = e j → i = j := by
  -- `choose` is a mathlib tactic; this repo is mathlib-free, so use core `Exists.choose`.
  have hex := fun k => h (succObj ℓ) (upRel ℓ k)
  refine ⟨fun k => (hex k).choose.g (0 : Nat), ?_⟩
  intro i j hij
  have hcls : ∀ k (n : Nat) (u : Unit),
      (upRel ℓ k).rel n u ↔ mem.rel ((hex k).choose.g n) u :=
    fun k => ((hex k).choose_spec).1
  have hall : ∀ n, (hex i).choose.g n = (hex j).choose.g n :=
    map_det ℓ (hex i).choose (hex j).choose hij
  have key : ∀ n, (i ≤ n) ↔ (j ≤ n) := by
    intro n
    have Hi := hcls i n ()
    have Hj := hcls j n ()
    rw [hall n] at Hi
    exact Hi.trans Hj.symm
  exact Nat.le_antisymm ((key j).2 (Nat.le_refl j)) ((key i).1 (Nat.le_refl i))

/-! ## §2.417  Concrete non-representability witnesses (target 3, the reachable form). -/

/-- **Concrete witness.**  The terminator `1` (a NON-coterminator) does not have the terminator
    itself as a power-object: no `mem : 1 → 1` makes `1` a power-object of `1`.  (Its power-object,
    if any, has an infinite carrier by `terminator_power_carrier_infinite`, but `1` has one point.)
    Contrast `coterminator_hasPowerObject` (`S2_417b_NotPower.lean`): the coterminator DOES have
    one.  This is the §1.96(10) dichotomy, one non-coterminator instance. -/
theorem terminator_oneObj_not_power (ℓ : L) (mem : CRel (oneObj L) (oneObj L)) :
    ¬ IsPowerObj (oneObj L) (oneObj L) mem := by
  intro h
  obtain ⟨e, hinj⟩ := terminator_power_carrier_infinite ℓ h
  -- `e : ℕ → Unit` injective forces `0 = 1`.
  have : (0 : Nat) = 1 := hinj 0 1 (unit_eq _ _)
  exact absurd this (by decide)

/-- **Reachability bridge to `RelCIsPowerAllegory`.**  If `Rel(C)` were a power allegory then the
    terminator would have a power-object, whose carrier is forced INFINITE (an injection from `ℕ`).
    This is a TRUE implication for every `L` — it does NOT refute `RelCIsPowerAllegory` (over a
    label SET `L` the terminator genuinely has the infinite sieve-object as its power-object; see
    header).  Freyd's `¬ RelCIsPowerAllegory` needs proper-class-many labels so that "infinite"
    becomes "a proper class", i.e. non-existent — not internalizable in Lean. -/
theorem powerAllegory_forces_infinite_terminator_power (ℓ : L)
    (h : RelCIsPowerAllegory L) :
    ∃ (P : Obj L) (_ : CRel P (oneObj L)) (e : Nat → P.S), ∀ i j, e i = e j → i = j := by
  obtain ⟨P, mem, hP⟩ := h (oneObj L)
  exact ⟨P, mem, terminator_power_carrier_infinite ℓ hP⟩

end Freyd.S2_417
